# ------------------- autoload theme ------------------------
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: darkorange
# ------------------- autoload theme ------------------------
# ------------------- cellar new --------------------------------
  - alias: cellar_light_on_motion
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev6_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev54_motion_2
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev6_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev54_motion_2
        to: 'on'
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev6_motion','on') or is_state('binary_sensor.dev54_motion_2','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev6
# ------------------- cellar new --------------------------------
# ------------------- living room sunset new -------------------
  - alias: joiner_livingroom_in2
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'on'
        - condition: state
          entity_id: 'binary_sensor.g_motion_10m'
          state: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.joiner_livingroom
# ----------------------------------------------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- alarm system ------------------------
# ----------------------------------------------------------
# --------------------- rearm new ------------------------------
  - alias: rearm_alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_is_home
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.alarm_System
# --------------------- rearm new ------------------------------
# --------------------- un-arm new ------------------------------
  - alias: dearm_alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: mqtt
        topic: "alarm/dearm"
    action:
      - service_template: >
          {% if trigger.payload=="ON" %} 
            homeassistant.turn_on
          {% else %} 
            homeassistant.turn_off
          {% endif %} 
        entity_id: input_boolean.alarm_System
# --------------------- un-arm ------------------------------
# ---------------------------------------------------------
# ------------------- value trigger for leakage new ------------
  - alias: 'leakage'
    initial_state: 'on'
    trigger:
     - platform: numeric_state
       entity_id: sensor.dev13_adc
       below: 500
    action:
     service: notify.pb
     data:
       title: "Leakage detected"
       message: "Leakage triggered"
# ------------------- value trigger for leakage ------------
# ------------------- value trigger for over temp new ----------
  - alias: 'over temp'
    initial_state: 'on'
    trigger:
     - platform: numeric_state
       entity_id: sensor.dev11_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev1_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev16_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev4_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev2_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev10_temperature
       above: 50
     - platform: numeric_state
       entity_id: sensor.dev9_temperature
       above: 50
    action:
     service: notify.pb
     data:
       title: "over temp detected"
       message: "over temp triggered"
# ------------------- value trigger for over temp ----------
# ----------------------------------------------------------

# ------------------- drivetime kolja new ----------------------
  - alias: inform_tavel_kolja
    initial_state: True
    hide_entity: False
    trigger:
      - platform: time_pattern
        hours: 6
        minutes: 00
        seconds: 00
    condition: # make sure that BOTH sensors show off
      - condition: numeric_state
        entity_id: sensor.to_baker
        above: 25
    action:
     service: notify.pb
     data_template:
       title: "Long traveltime"
       message: "Currently {{ states.sensor.to_baker.state }} min traveltime"
# ------------------- drivetime kolja ----------------------

#-------------------- night lights -------------------------
  - alias: night_light
    initial_state: True
    hide_entity: False
    trigger:
      - platform: sun           # off 5 min after sunrise
        event: sunrise
        offset: "+00:0:00"
      - platform: sun           # on 5 min after sunset
        event: sunset
        offset: "+00:5:00"
    action:
      - service_template: >
          {% if is_state('sun.sun','below_horizon') %} 
            light.turn_on                
          {% else %} 
            light.turn_off
          {% endif %}
        entity_id: 
          - light.night
#-------------------- new kitchen -------------------------
#  - alias: new_kitchen_in
#    initial_state: True
#    hide_entity: False
#    trigger:
#      - platform: state
#        entity_id: light.dev3
#    action:
#      - service_template: >
#          {% if is_state('light.dev3','on') %}
#            light.turn_on
#          {% else %}
#            light.turn_off
#          {% endif %}
#        entity_id: 
#          - light.dev21
#-------------------- new kitchen -------------------------
