# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: dev2_4_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'on'
      - platform: state
        entity_id: light.dev4
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev2
          - light.dev4
# ----------------------------------------------------------
  - alias: dev2_4_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'off'
      - platform: state
        entity_id: light.dev4
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev2
          - light.dev4
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: dev7_11_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev7
        to: 'on'
      - platform: state
        entity_id: light.dev11
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev7
          - light.dev11
# ----------------------------------------------------------
  - alias: dev7_11_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev7
        to: 'off'
      - platform: state
        entity_id: light.dev11
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev7
          - light.dev11
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: sunset_dev7_dev11
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:15:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.7c11cba3f1d1'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.64bc0c4df830'
          state: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: light.dev7
      - service: homeassistant.turn_on
        entity_id: light.dev11
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: Turn_on_kitchen_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: script.kitchen_lamp_on
# ----------------------------------------------------------
  - alias: Turn_off_kitchen_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'off'
    action:
      service: homeassistant.turn_on
      entity_id: script.kitchen_lamp_off
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: sunset_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:15:00"
    condition:
      platform: time
      before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.dev5
# ----------------------------------------------------------
  - alias: midnight_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      hours: 23
      minutes: 30
      seconds: 00
    action:
      - service: homeassistant.turn_off
        entity_id: light.dev5
# ----------------------------------------------------------
# ----------------------------------------------------------
