# ------------------- autoload theme ------------------------
  - alias: 'Set theme at startup'
    initial_state: 'on'
    trigger:
     - platform: homeassistant
       event: start
    action:
      service: frontend.set_theme
      data:
        name: darkorange
# ------------------- autoload theme ------------------------

# ------------------- entrance Room ------------------------
  - alias: entranceRoom
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 2 min
      - platform: state
        entity_id: binary_sensor.dev6_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 2
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev6_motion
        to: 'on'
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev6_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev12
# ------------------- entrance Room ------------------------
# ------------------- carlo --------------------------------
  - alias: carlo_test
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev8_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev8_motion
        to: 'on'
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev8_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev55
# ------------------- carlo --------------------------------
# ------------------- living room sunset -------------------
  - alias: joiner_livingroom_in2
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'on'
        - condition: state
          entity_id: 'binary_sensor.g_motion_10m'
          state: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.joiner_livingroom
# ------------------- living joiner out -------------------
  - alias: joiner_livingroom_out
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_livingroom
    action:
      - service_template: >
          {% if is_state('light.joiner_livingroom','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev1
          - light.dev7
          - light.dev11
          - light.dev21  
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: joiner_bedroom_in
    initial_state: True
    hide_entity: False
    trigger:
      - platform: mqtt
        topic: "dev16/r/button"
      - platform: mqtt
        topic: "dev20/r/button"
      - platform: mqtt
        topic: "dev3/r/button"
    action:
      service: light.toggle
      entity_id: light.joiner_bedroom
# ----------------------------------------------------------
  - alias: joiner_bedroom_in2
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:15:00"
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - light.joiner_bedroom
# ----------------------------------------------------------
  - alias: joiner_bedroom_out
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_bedroom
    action:
      - service_template: >
          {% if is_state('light.joiner_bedroom','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev20
          - light.dev3
          - light.dev16  
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: joiner_kitchen_in
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'on'
    action:
      service: light.turn_on
      entity_id: light.joiner_kitchen
# ----------------------------------------------------------
  - alias: joiner_kitchen_in2
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    condition: # make sure that BOTH sensors show off
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.dev4_motion
          state: 'off'
          for: 
              hours: 0
              minutes: 10
              seconds: 0
        - condition: state
          entity_id: binary_sensor.dev14_motion
          state: 'off'
          for: 
              hours: 0
              minutes: 10
              seconds: 0
    action:
      service: light.turn_off
      entity_id: light.joiner_kitchen
# ------------------- kitchen movement ---------------------
# ----------------------------------------------------------
# ----------------------------------------------------------
  - alias: joiner_kitchen_out
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_kitchen
    action:
      - service_template: >
          {% if is_state('light.joiner_kitchen','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev2
          - light.dev4
          - light.dev14  
# ----------------------------------------------------------
# ----------------------------------------------------------
# ------------------- couch  movement ---------------------
  - alias: couch_automation
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev101_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev101 
# ------------------- couch  movement ---------------------
# ----------------------------------------------------------
# ------------------- entrance  movement -------------------
  - alias: entrance_automation
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev102_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev102 
# ------------------- entrace  movement -------------------
# ----------------------------------------------------------
# ------------------- tv  movement -------------------
  - alias: tv_automation
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev103_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev103 
# ------------------- tv  movement -------------------
# ----------------------------------------------------------
# ------------------- dragonfly  movement -------------------
  - alias: dragonfly_automation
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev106_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev106 
# ------------------- dragonfly  movement -------------------
# ----------------------------------------------------------
# -------------------- hallway movement --------------------
# ------ Turn_on_hallwayU_lights_when_there_is_movement ----
  - alias: joiner_hallwayU_in
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 2
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev10_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.joiner_hallwayU 
# ----------------------------------------------------------
# -- alias: Turn_off_hallwayU_lights_10min_after_movement --
  - alias: joiner_hallwayU_in2
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.joiner_bedroom
        to: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.joiner_hallwayU
# ----------------------------------------------------------
  - alias: joiner_hallwayU_out
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_hallwayU
    action:
      - service_template: >
          {% if is_state('light.joiner_hallwayU','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev10
# ----------------------------------------------------------
# ----------------------------------------------------------
# -- alias: Turn_on_hallwayD_lights_when_there_is_movement -
  - alias: joiner_hallwayD_in
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
    action:
      - service_template: >
          {% if is_state('binary_sensor.dev15_motion','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.joiner_hallwayD
# ----------------------------------------------------------
  - alias: joiner_hallwayD_out
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_hallwayD
    action:
      - service_template: >
          {% if is_state('light.joiner_hallwayD','on') %}
            light.turn_on
          {% else %}
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev56
          - light.dev15
# ----------------------------------------------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- alarm system ------------------------
# ----------------------------------------------------------
# --------------------- rearm ------------------------------
  - alias: rearm_alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_is_home
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.alarm_System
# --------------------- rearm ------------------------------
# ----------------------------------------------------------
# --------------------- gmotion ----------------------------
# send message as soon as there is movement and nobody is home
  - alias: alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.g_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
     service: notify.pb
     data:
       title: "Motion detected"
       message: "GMotion triggered"
# --------------------- gmotion ----------------------------
# --------------------- 101 --------------------------------
  - alias: alarm_system_c101 
    initial_state: False
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_101
# --------------------- 101 --------------------------------
# --------------------- 102 --------------------------------
  - alias: alarm_system_c102 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_102
# --------------------- 102 --------------------------------
# --------------------- 103 --------------------------------
  - alias: alarm_system_c103 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_103
# --------------------- 103 --------------------------------
# --------------------- 106 --------------------------------
  - alias: alarm_system_c106 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_106
# --------------------- 106 --------------------------------
# --------------------- alarm system -----------------------
# ----------------------------------------------------------

# ------------------- value trigger for leakage ------------------------
  - alias: 'leakage'
    initial_state: 'on'
    trigger:
     - platform: numeric_state
       entity_id: sensor.dev13_adc
       below: 500
    action:
     service: notify.pb
     data:
       title: "Leakage detected"
       message: "Leakage triggered"
# ------------------- value trigger for leakage ------------------------

# ------------------- outdoor light ------------------------
  - alias: outdoor_light2
    initial_state: True
    hide_entity: False
    trigger:
      - platform: time          # on at 6:30
        hours: 6
        minutes: 30
        seconds: 00
      - platform: sun           # off 30 min after sunrise
        event: sunrise
        offset: "+00:30:00"
      - platform: sun           # on 15 min after sunset
        event: sunset
        offset: "+00:15:00"
      - platform: state         # off when everyone is home after 22:00, triggered by presents (if that happens after 22:00)
        entity_id: binary_sensor.everyone_is_home
        to: 'on'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: time          # off when everyone is home after 22:00, triggered by time (if everyone was home already)
        hours: 22
        minutes: 00
        seconds: 10
      - platform: time          # off for sure after 23:00
        hours: 23
        minutes: 00
        seconds: 01
    action:
          # sun below horizon and time>23:00: off
          # sun below horizon and time>22:00 and everyone home: off
          # sun below horizon and time<22:00 on no matter who is home
          # time>6:30 and sun still below horizon: on
          #
      - service_template: >
          {% if now().hour==23 %} 
            light.turn_off
          {% elif is_state('sun.sun','below_horizon') and now().hour>=22 and is_state('binary_sensor.everyone_is_home','on') %} 
            light.turn_off                
          {% elif is_state('sun.sun','below_horizon') %}
            light.turn_on 
          {% else %} 
            light.turn_off
          {% endif %}
        entity_id: 
          - light.dev5
# ------------------- outdoor light ------------------------
