  - alias: next_track_lirc
    initial_state: True
    hide_entity: False
    trigger:
      platform: event
      event_type: ir_command_received
      event_data:
        button_name: KEY_RIGHT
    action:
      service: media_player.media_next_track
      entity_id: media_player.jkw_cast2
# ----------------------------------------------------------
# ----------------------------------------------------------
# ------------------ gmusic player -------------------------
  - alias: g_radion_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: switch.background
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.seq_gradio_on
# ----------------------------------------------------------
  - alias: g_radion_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: switch.background
        to: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_gradio_off
# ------------------ gmusic player -------------------------
# ----------------------------------------------------------
# ------------------ kitchen joiner ------------------------
  - alias: dev2_4_14_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'on'
      - platform: state
        entity_id: light.dev4
        to: 'on'
      - platform: state
        entity_id: light.dev14
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev2
          - light.dev4
          - light.dev14
# ----------------------------------------------------------
  - alias: dev2_4_14_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'off'
      - platform: state
        entity_id: light.dev14
        to: 'off'
      - platform: state
        entity_id: light.dev4
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev2
          - light.dev4
          - light.dev14
# ------------------ kitchen joiner ------------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------ bedroom joiner ------------------------
  - alias: dev16_20_on
    initial_state: True
    hide_entity: False
    trigger:
#      - platform: state
#        entity_id: light.dev20
#        to: 'on'
      - platform: state
        entity_id: light.dev16
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev20
#          - light.dev16
# ----------------------------------------------------------
  - alias: dev16_20_off
    initial_state: True
    hide_entity: False
    trigger:
 #     - platform: state
 #       entity_id: light.dev20
 #       to: 'off'
      - platform: state
        entity_id: light.dev16
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev20
#          - light.dev16
# ------------------ bedroom joiner ------------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------ living room joiner --------------------
  - alias: dev7_11_1_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev7
        to: 'on'
      - platform: state
        entity_id: light.dev1
        to: 'on'
      - platform: state
        entity_id: light.dev11
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev1
          - light.dev7
          - light.dev11
# ----------------------------------------------------------
  - alias: dev7_11_1_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev1
        to: 'off'
      - platform: state
        entity_id: light.dev7
        to: 'off'
      - platform: state
        entity_id: light.dev11
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev1
          - light.dev7
          - light.dev11
# ------------------ living room joiner --------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------- living room sunset -------------------
  - alias: sunset_dev7_dev11_dev1
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:30:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'on'
        - condition: state
          entity_id: 'binary_sensor.g_motion_10m'
          state: 'on'
    action:
      - service: homeassistant.turn_on
        entity_id: 
          - light.dev1
          - light.dev7
          - light.dev11
# ------------------- living room sunset -------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------- bedroom sunrise ----------------------
  - alias: sunrise_dev20
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunrise
      offset: "+00:15:00"
    action:
      - service: homeassistant.turn_off
        entity_id: 
          - light.dev20
# ------------------- bedroom sunrise ----------------------
# ----------------------------------------------------------



# ----------------------------------------------------------
# ------------------- kitchen movement ---------------------
  - alias: Turn_on_kitchen_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev14 # turn only one on, all others will follow
# ----------------------------------------------------------
  - alias: Turn_off_kitchen_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    condition: # make sure that BOTH sensors show off
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.dev4_motion
          state: 'off'
        - condition: state
          entity_id: binary_sensor.dev14_motion
          state: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.dev14 # turn only one on, all others will follow
# ------------------- kitchen movement ---------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------- living  movement ---------------------
  - alias: Turn_on_couch_light_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev101 
# ----------------------------------------------------------
  - alias: Turn_off_couch_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev101 
# ------------------- living  movement ---------------------
# ------------------- entrance  movement -------------------
  - alias: Turn_on_couch_light_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev102 
# ----------------------------------------------------------
  - alias: Turn_off_entrance_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev102 
# ------------------- entrace  movement -------------------
# ------------------- tv  movement ------------------------
  - alias: Turn_on_tv_light_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev103
# ----------------------------------------------------------
  - alias: Turn_off_tv_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev103 
# ----------------------- tv  movement ---------------------
# ------------------- dragonfly  movement ------------------
  - alias: Turn_on_dragonfly_light_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev106 
# ----------------------------------------------------------
  - alias: Turn_off_dragonfly_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev106 
# ------------------- dragonfly  movement ------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- hallway movement --------------------
  - alias: Turn_on_hallwayU_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'on'
#    condition:
#      condition: and
#      conditions:
#        - condition: time
#          after: '06:30:00'
#        - condition: time
#          before: '23:30:00'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev10
# ----------------------------------------------------------
  - alias: Turn_off_hallwayU_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 2
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev10
# ----------------------------------------------------------
  - alias: Turn_on_hallwayD_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev15
# ----------------------------------------------------------
  - alias: Turn_off_hallwayD_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev15
# -------------------- hallway movement --------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- outside on dark ---------------------
# switch the light on, 15 min after sunset, but only if thats before 23:30
  - alias: sunset_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "+00:15:00"
    condition:
      condition: time
      before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.dev5
# ----------------------------------------------------------
# turn the lights off if both of us are at home for at least 10min and it is after 22:00
  - alias: all_home_dev5
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.everyone_is_home
        to: 'on'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: time
        hours: 22
        minutes: 00
        seconds: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.everyone_is_home
          state: 'on'
        - condition: time
          after: '22:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: light.dev5
# ----------------------------------------------------------
# turn the lights of at 23:30
  - alias: midnight_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      hours: 23
      minutes: 30
      seconds: 00
    action:
      - service: homeassistant.turn_off
        entity_id: light.dev5
# -------------------- outside on dark ---------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- alarm system ------------------------
# ----------------------------------------------------------
# --------------------- rearm ------------------------------
  - alias: rearm_alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_is_home
        to: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.alarm_System
# --------------------- rearm ------------------------------
# ----------------------------------------------------------
# --------------------- gmotion ----------------------------
# send message as soon as there is movement and nobody is home
  - alias: alarm_system
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.g_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
     service: notify.pb
     data:
       title: "Motion detected"
       message: "GMotion triggered"
# --------------------- gmotion ----------------------------
# --------------------- 101 --------------------------------
  - alias: alarm_system_c101 
    initial_state: False
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev101_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_101
# --------------------- 101 --------------------------------
# --------------------- 102 --------------------------------
  - alias: alarm_system_c102 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev102_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_102
# --------------------- 102 --------------------------------
# --------------------- 103 --------------------------------
  - alias: alarm_system_c103 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev103_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_103
# --------------------- 103 --------------------------------
# --------------------- 106 --------------------------------
  - alias: alarm_system_c106 
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev106_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_106
# --------------------- 106 --------------------------------
# --------------------- alarm system -----------------------
# ----------------------------------------------------------


# --------- playground --------
  - alias: set_dimmer
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: input_slider.dev12_dimmer_delay
    action:
      service: mqtt.publish
      data_template:
        topic: "dev12/PWM_dimm/delay/set"
        retain: true
        payload: '{{ states.input_slider.dev12_dimmer_delay.state | int }}'

# ------
  - alias: test
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev99_motion
        to: 'on'
    action: 
      service: mqtt.publish
      data:
        topic: "owntracks/illuminum/kolja/cmd"
        payload: "{\"_type\":\"cmd\",\"action\":\"reportLocation\"}"
