# ----------------------------------------------------------
# ------------------ kitchen joiner ------------------------
  - alias: dev2_4_14_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'on'
      - platform: state
        entity_id: light.dev4
        to: 'on'
      - platform: state
        entity_id: light.dev14
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev2
          - light.dev4
          - light.dev14
# ----------------------------------------------------------
  - alias: dev2_4_14_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev2
        to: 'off'
      - platform: state
        entity_id: light.dev14
        to: 'off'
      - platform: state
        entity_id: light.dev4
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev2
          - light.dev4
          - light.dev14
# ------------------ kitchen joiner ------------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------ living room joiner --------------------
  - alias: dev7_11_1_on
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev7
        to: 'on'
      - platform: state
        entity_id: light.dev1
        to: 'on'
      - platform: state
        entity_id: light.dev11
        to: 'on'
    action:
      - service: light.turn_on
        entity_id: 
          - light.dev1
          - light.dev7
          - light.dev11
# ----------------------------------------------------------
  - alias: dev7_11_1_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: light.dev1
        to: 'off'
      - platform: state
        entity_id: light.dev7
        to: 'off'
      - platform: state
        entity_id: light.dev11
        to: 'off'
    action:
      - service: light.turn_off
        entity_id:
          - light.dev1
          - light.dev7
          - light.dev11
# ------------------ living room joiner --------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# ------------------- living room sunset -------------------
  - alias: sunset_dev7_dev11_dev1
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "-00:15:00"
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.7c11cba3f1d1'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.64bc0c4df830'
          state: 'home'
    action:
      - service: homeassistant.turn_on
        entity_id: 
          - light.dev1
          - light.dev7
          - light.dev11
# ------------------- living room sunset -------------------
# ----------------------------------------------------------


# ----------------------------------------------------------
# ------------------- kitchen movement ---------------------
  - alias: Turn_on_kitchen_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'on'
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev14 # turn only one on, all others will follow
# ----------------------------------------------------------
  - alias: Turn_off_kitchen_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger: # trigger twice, whenever the motion sensors are off for 10min
      - platform: state
        entity_id: binary_sensor.dev4_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
      - platform: state
        entity_id: binary_sensor.dev14_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 10
          seconds: 0
    condition: # make sure that BOTH sensors show off
      condition: and
      conditions:
        - condition: state
          entity_id: binary_sensor.dev4_motion
          state: 'off'
        - condition: state
          entity_id: binary_sensor.dev14_motion
          state: 'off'
    action:
      service: homeassistant.turn_off
      entity_id: light.dev14 # turn only one on, all others will follow
# ------------------- kitchen movement ---------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- hallway movement --------------------
  - alias: Turn_on_hallwayU_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30:00'
        - condition: time
          before: '23:30:00'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev10
# ----------------------------------------------------------
  - alias: Turn_off_hallwayU_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev10_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 2
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev10
# ----------------------------------------------------------
  - alias: Turn_on_hallwayD_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'on'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev15
# ----------------------------------------------------------
  - alias: Turn_off_hallwayD_lights_10min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev15_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev15
# -------------------- hallway movement --------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- bedroom movement --------------------
  - alias: Turn_on_bedroom_lights_when_there_is_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev16_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '06:30:00'
        - condition: time
          before: '22:30:00'
    action:
      service: homeassistant.turn_on
      entity_id: light.dev16
# ----------------------------------------------------------
  - alias: Turn_off_bedroom_lights_5min_after_movement
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev16_motion
        to: 'off'
        for: 
          hours: 0
          minutes: 5
          seconds: 0
    action:
      service: homeassistant.turn_off
      entity_id: light.dev16
# -------------------- hallway movement --------------------
# ----------------------------------------------------------

# ----------------------------------------------------------
# -------------------- outside on dark ---------------------
# switch the light on, 15 min after sunset, but only if that before 23:30
  - alias: sunset_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: sun
      event: sunset
      offset: "+00:15:00"
    condition:
      condition: time
      before: '23:30:00'
    action:
      - service: homeassistant.turn_on
        entity_id: light.dev5
# ----------------------------------------------------------
# turn the lights off if both of us are at home and it is after 22:00
  - alias: all_home_dev5
    initial_state: True
    hide_entity: False
    trigger:
      - platform: state
        entity_id: 'device_tracker.64bc0c4df830'
        to: 'home'
      - platform: state
        entity_id: 'device_tracker.7c11cba3f1d1'
        to: 'home'
      - platform: time
        hours: 22
        minutes: 00
        seconds: 10
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.7c11cba3f1d1'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.64bc0c4df830'
          state: 'home'
        - condition: time
          after: '22:00:00'
    action:
      - service: homeassistant.turn_off
        entity_id: light.dev5
# ----------------------------------------------------------
# turn the lights of at 23:30
  - alias: midnight_dev5
    initial_state: True
    hide_entity: False
    trigger:
      platform: time
      hours: 23
      minutes: 30
      seconds: 00
    action:
      - service: homeassistant.turn_off
        entity_id: light.dev5
# -------------------- outside on dark ---------------------
# ----------------------------------------------------------


# --------- playground --------
  - alias: set_dimmer
    initial_state: True
    hide_entity: False
    trigger:
      platform: state
      entity_id: input_slider.dev12_dimmer_delay
    action:
      service: mqtt.publish
      data_template:
        topic: "dev12/PWM_dimm/delay/set"
        retain: true
        payload: '{{ states.input_slider.dev12_dimmer_delay.state | int }}'
