homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 51
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  whitelist_external_dirs:
   - /tmp
   - /mnt
  customize: !include customize.yaml
  packages: !include_dir_named packages

zone 3:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:account-multiple

# Enables the frontend
frontend:

http:
  api_password: !secret http_password


notify:
  name: pb
  platform: pushbullet
  api_key: !secret pushbullet_key

# Checks for available updates
updater:

# Discover some devices automatically
discovery:
lirc:
remote:
  - platform: harmony
    name: TVHub
    host: 192.168.2.164

history:

recorder:
  db_url: mysql://ha:ah@localhost/ha
  purge_days: 5

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
 platform: google

# button
input_boolean:
  alarm_system:
    name: "Global Alarm enabled"
    initial: on
    icon: mdi:security-home

mqtt:
 broker: 127.0.0.1
 port: 1883
 client_id: home-assistant-1
 username: !secret mq_user
 password: !secret mq_pass

media_player:
 - platform: cast
   host: 192.168.2.134
emulated_hue:
 listen_port: 80

# Weather Prediction
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
light: !include lights.yaml
device_tracker: !include tracker.yaml
binary_sensor: !include b_sensors.yaml
input_slider: !include slider.yaml

automation: !include automation.yaml
script: !include scripts.yaml

camera:
  - name: map_caro
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.illuminum_caro.attributes.latitude }},{{ states.device_tracker.illuminum_caro.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.illuminum_caro.attributes.latitude }},{{ states.device_tracker.illuminum_caro.attributes.longitude }}
    limit_refetch_to_url_change: true

  - name: map_kolja
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.illuminum_kolja.attributes.latitude }},{{ states.device_tracker.illuminum_kolja.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.illuminum_kolja.attributes.latitude }},{{ states.device_tracker.illuminum_kolja.attributes.longitude }}
    limit_refetch_to_url_change: true

  - name: cam_101
    platform: generic
    still_image_url: http://192.168.2.101/cam_full.jpg

  - name: cam_102
    platform: generic
    still_image_url: http://192.168.2.102/cam_full.jpg

  - name: cam_103
    platform: generic
    still_image_url: http://192.168.2.103/cam_full.jpg

  - name: cam_106
    platform: generic
    still_image_url: http://192.168.2.106/cam_full.jpg


shell_command:
  cam1_1: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_1.jpg
  cam1_2: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_2.jpg
  cam1_3: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_3.jpg
  cam1_4: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_4.jpg
  cam1_5: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_5.jpg

  cam2_1: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_1.jpg
  cam2_2: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_2.jpg
  cam2_3: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_3.jpg
  cam2_4: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_4.jpg
  cam2_5: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_5.jpg
  
  cam3_1: wget http://192.168.2.103/cam_full.jpg -O /tmp/103_1.jpg
  cam3_2: wget http://192.168.2.103/cam_full.jpg -O /tmp/103_2.jpg
  cam3_3: wget http://192.168.2.103/cam_full.jpg -O /tmp/103_3.jpg
  cam3_4: wget http://192.168.2.103/cam_full.jpg -O /tmp/103_4.jpg
  cam3_5: wget http://192.168.2.103/cam_full.jpg -O /tmp/103_5.jpg
    
  cam6_1: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_1.jpg
  cam6_2: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_2.jpg
  cam6_3: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_3.jpg
  cam6_4: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_4.jpg
  cam6_5: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_5.jpg
  
