homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 52.4137
  longitude: 9.7544
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 51
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin

  customize: !include customize.yaml

# database connection


# Enables the frontend
frontend:

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
# remember to install mysql in the virtual dev
history:
recorder:
  db_url: mysql://user:pw@localhost/ha

# View all events in a logbook
logbook:

# Track the sun
sun:

# Text to speech
tts:
 platform: google


mqtt:
 broker: 127.0.0.1
 port: 1883
 client_id: home-assistant-1
 username: ha
 password: ah

media_player:
  - platform: cast

# Weather Prediction
sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
light: !include lights.yaml
device_tracker: !include tracker.yaml
binary_sensor: !include b_sensors.yaml

automation: !include automation.yaml
script: !include scripts.yaml


