homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 51
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  whitelist_external_dirs:
   - /tmp
   - /mnt
  customize: !include customize.yaml
  packages: !include_dir_named packages

lovelace:
  mode: yaml
config:
zone 3:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:account-multiple

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-floorplan.html
    - /local/kitchen.jpg
    - /local/livingroom.jpg
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  javascript_version: auto

#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml


http:
  api_password: !secret http_password
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem


notify:
  - name: pb
    platform: pushbullet
    api_key: !secret pushbullet_key
    base_url: https://kolja.duckdns.org:8123
  - name: pb_c
    platform: pushbullet
    api_key: !secret pushbullet_key_c
    base_url: https://kolja.duckdns.org:8123

remote:
  - platform: harmony
    name: TVHub
    host: 192.168.2.44

updater:
discovery:
history:
recorder:
  db_url: sqlite:////dev/shm/ha.sql
  purge_keep_days: 2
logbook:
sun:
system_health:
stream:
emulated_hue:


# button
input_boolean:
  alarm_system:
    name: "Global Alarm enabled"
    initial: on
    icon: mdi:security
  presents_simulation:
    name: "Presents simulation"
    initial: off
    icon: mdi:airballoon

mqtt:
 broker: 127.0.0.1
 port: 1883
 username: !secret mq_user
 password: !secret mq_pass


sensor: !include sensors.yaml
switch: !include switches.yaml
light: !include lights.yaml
device_tracker: !include tracker.yaml
binary_sensor: !include b_sensors.yaml
automation: !include automation.yaml
script: !include scripts.yaml

camera:
  - name: pi103
    platform: generic
    still_image_url: http://192.168.2.103/cam_full.jpg
  - name: pi106
    platform: generic
    still_image_url: http://192.168.2.106/cam_full.jpg



