homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 51
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  whitelist_external_dirs:
   - /tmp
   - /mnt
  customize: !include customize.yaml
  packages: !include_dir_named packages

config:
zone 3:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  radius: 500
  icon: mdi:account-multiple

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/
  extra_html_url:
    - /local/custom_ui/state-card-tiles.html
    - /local/custom_ui/state-card-floorplan.html
    - /local/kitchen.jpg
    - /local/livingroom.jpg
  extra_html_url_es5:
    - /local/custom_ui/state-card-tiles_es5.html
  javascript_version: auto

#panel_custom:
#  - name: floorplan
#    sidebar_title: Floorplan
#    sidebar_icon: mdi:home
#    url_path: floorplan
#    config: !include floorplan.yaml


http:
  api_password: !secret http_password
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem


notify:
  - name: pb
    platform: pushbullet
    api_key: !secret pushbullet_key
    base_url: https://kolja.duckdns.org:8123
  - name: pb_c
    platform: pushbullet
    api_key: !secret pushbullet_key_c
    base_url: https://kolja.duckdns.org:8123

remote:
  - platform: harmony
    name: TVHub
    host: 192.168.2.44

updater:
discovery:
history:
recorder:
logbook:
sun:

emulated_hue:

# Text to speech
tts:
 platform: google

# button
input_boolean:
  alarm_system:
    name: "Global Alarm enabled"
    initial: on
    icon: mdi:security-home

mqtt:
 broker: 127.0.0.1
 port: 1883
 client_id: home-assistant-1
 username: !secret mq_user
 password: !secret mq_pass

media_player:
 - platform: cast
   host: 192.168.2.39
 - platform: cast
   host: 192.168.2.55
 - platform: cast
   host: 192.168.2.22

sensor: !include sensors.yaml
switch: !include switches.yaml
group: !include groups.yaml
light: !include lights.yaml
device_tracker: !include tracker.yaml
binary_sensor: !include b_sensors.yaml
automation: !include automation.yaml
script: !include scripts.yaml

camera:
  - name: map_caro
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.illuminum_caro.attributes.latitude }},{{ states.device_tracker.illuminum_caro.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.illuminum_caro.attributes.latitude }},{{ states.device_tracker.illuminum_caro.attributes.longitude }}
    limit_refetch_to_url_change: true

  - name: map_kolja
    platform: generic
    still_image_url: https://maps.googleapis.com/maps/api/staticmap?center={{ states.device_tracker.illuminum_kolja.attributes.latitude }},{{ states.device_tracker.illuminum_kolja.attributes.longitude }}&zoom=13&size=500x500&maptype=roadmap&markers=color:blue%7Clabel:P%7C{{ states.device_tracker.illuminum_kolja.attributes.latitude }},{{ states.device_tracker.illuminum_kolja.attributes.longitude }}
    limit_refetch_to_url_change: true

weather:
  - platform: darksky
    api_key: !secret darksky_key


