automation:
  alias: deadman_reset
  trigger: 
    platform: time_pattern
    # You can also match on interval. This will match every 5 minutes
    minutes: "/5"
  action:
    service: rest_command.reset_deadman
    data:
      token: !secret deadmantoken

rest_command:
   reset_deadman:
      url: "https://hc-ping.com/{{token}}"
