### Garage living room
# SL, DS18B20
# -----------------------------------------------
switch:
  - platform: mqtt ### tower dinning
    name: "dev8"
    command_topic: "dev8/s/gpio_14_pulse"
    state_topic: "dev8/r/light"
    qos: 0
    retain: False
    payload_on: "300"
    payload_off: "OFF"

# -----------------------------------------------


homeassistant:
  customize:
    light.dev8:
      friendly_name: "Garage"
    binary_sensor.dev8_button:
      friendly_name: "Garage button"
    binary_sensor.dev8_button1s:
      friendly_name: "Garage button1s"
    binary_sensor.dev8_motion:
      friendly_name: "Garage motion"
      device_class: motion
    sensor.dev8_temperature:
      friendly_name: "Garage temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev8_adc:
      friendly_name: "Garage"
    switch.dev8:
      friendly_name: "Garage"
      icon: "mdi:boom-gate"
    switch.dev8_gpio_14:
      friendly_name: "Garage_ignore"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev8"
    fname: "08 Garage"


# -----------------------------------------------

