# -----------------------------------------------

homeassistant:
  customize:
    light.dev35:
      friendly_name: "Heater main"
    binary_sensor.dev35_button:
      friendly_name: "Heater main button"
    binary_sensor.dev35_button1s:
      friendly_name: "Heater main button1s"
    binary_sensor.dev35_motion:
      friendly_name: "Heater main motion"
      device_class: motion
    sensor.dev35_temperature:
      friendly_name: "Heater main temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev35_adc:
      friendly_name: "Heater main"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev35"
    fname: "35 Heater main"

# -----------------------------------------------
