# -----------------------------------------------

homeassistant:
  customize:
    switch.dev58_gpio_12:
      friendly_name: "MediaPC"
    binary_sensor.dev58_button:
      friendly_name: "MediaPC button"
    binary_sensor.dev58_button1s:
      friendly_name: "MediaPC button1s"
    binary_sensor.dev58_motion:
      friendly_name: "MediaPC motion"
      device_class: motion
    sensor.dev58_temperature:
      friendly_name: "MediaPC temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev58_adc:
      friendly_name: "MediaPC"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev58"
    fname: "58 MediaPC"

# -----------------------------------------------

binary_sensor:
  - platform: ping
    name: mediapc_ping
    host: 192.168.2.35

# -----------------------------------------------

switch:
  - platform: command_line
    switches:
      mediapc_shutdown:
        command_off: net rpc shutdown -I 192.168.2.53 -U kolja%123

