
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev23"
    fname: "23 Carlo"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev23:
      friendly_name: "Carlo"

# -----------------------------------------------

input_boolean:
  carlo_switch_lock:
    name: Carlo light lock
    initial: off
    icon: mdi:lock
