# -----------------------------------------------

homeassistant:
  customize:
    light.dev9:
      friendly_name: "Foyer"
    binary_sensor.dev9_button:
      friendly_name: "Foyer button"
    binary_sensor.dev9_button1s:
      friendly_name: "Foyer button1s"
    binary_sensor.dev9_gpio_4:
      friendly_name: "Foyer motion"
      device_class: motion
    binary_sensor.dev9_gpio_5:
      friendly_name: "Dresser motion"
      device_class: motion
    sensor.dev9_temperature:
      friendly_name: "Foyer temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev9_adc:
      friendly_name: "Foyer"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev9"
    fname: "9 Foyer"

# -----------------------------------------------
