# -----------------------------------------------

homeassistant:
  customize:
    light.dev7:
      friendly_name: "Tower L"
      retain: True
    binary_sensor.dev7_button:
      friendly_name: "Tower L button"
    binary_sensor.dev7_button7s:
      friendly_name: "Tower L button7s"
    binary_sensor.dev7_motion:
      friendly_name: "Tower L motion"
      device_class: motion
    sensor.dev7_temperature:
      friendly_name: "Tower L temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev7"
    fname: "07 Tower L"

# -----------------------------------------------
