# -----------------------------------------------

homeassistant:
  customize:
    light.dev5:
      friendly_name: "Kitchen Kronleuchter"
      retain: True
    binary_sensor.dev5_button:
      friendly_name: "Kitchen Kronleuchter button"
    binary_sensor.dev5_button1s:
      friendly_name: "Kitchen Kronleuchter button1s"
    binary_sensor.dev5_motion:
      friendly_name: "Kitchen Kronleuchter motion"
      device_class: motion
    sensor.dev5_temperature:
      friendly_name: "Kitchen Kronleuchter temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev5"
    fname: "05 Kitchen Kronleuchter"

# -----------------------------------------------
