### touch bedroom
# SL
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev24"
    fname: "24 L Main"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev24:
      friendly_name: "L main"

