# -----------------------------------------------

homeassistant:
  customize:
    light.dev21:
      friendly_name: "SL Kitchen"
      retain: True
    binary_sensor.dev21_button:
      friendly_name: "SL Kitchen button"
    binary_sensor.dev21_button1s:
      friendly_name: "SL Kitchen button1s"
    binary_sensor.dev21_motion:
      friendly_name: "SL Kitchen motion"
      device_class: motion
    sensor.dev21_temperature:
      friendly_name: "SL Kitchen temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev21"
    fname: "21 SL Kitchen"

# -----------------------------------------------
