### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### outdoor 1
    name: "dev5"
    state_topic: "dev5/simple_light/status"
    command_topic: "dev5/simple_light/switch"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev5"
    fname: "05 Front Door"

# -----------------------------------------------
