### ball living room
# SL
# -----------------------------------------------

switch:
  - platform: mqtt ### autostart fakesensor
    name: "dev17_gpio_12_autostart"
    command_topic: "dev17/s/light_autostart"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

homeassistant:
  customize:
    switch.dev17_gpio_12:
      friendly_name: "Water pump"
      icon: mdi:water-pump

    switch.dev17_gpio_12_autostart:
      friendly_name: "Water Auto"
      icon: mdi:water-pump

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev17"
    fname: "17 Water pump"

# -----------------------------------------------

automation:
  - alias: pump_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: mqtt
        topic: irrigation
        payload: 'off'
    action:
      - service: light.turn_off
        entity_id: switch.dev17_gpio_12


# -----------------------------------------------

