# -----------------------------------------------

homeassistant:
  customize:
    light.dev10:
      friendly_name: "Beamer LED"
    binary_sensor.dev10_button:
      friendly_name: "Beamer LED button"
    binary_sensor.dev10_button1s:
      friendly_name: "Beamer LED button1s"
    binary_sensor.dev10_motion:
      friendly_name: "Beamer LED motion"
      device_class: motion
    sensor.dev10_temperature:
      friendly_name: "Beamer LED temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev10_adc:
      friendly_name: "Beamer LED"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev10"
    fname: "10 Beamer LED"

# -----------------------------------------------
