# -----------------------------------------------

homeassistant:
  customize:
    light.dev18:
      friendly_name: "PI"
    binary_sensor.dev18_button:
      friendly_name: "PI button"
    binary_sensor.dev18_button18s:
      friendly_name: "PI button1s"
    binary_sensor.dev18_motion:
      friendly_name: "PI motion"
      device_class: motion
    sensor.dev18_temperature:
      friendly_name: "PI temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev18_adc:
      friendly_name: "PI"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev18"
    fname: "18 PI"

# -----------------------------------------------
