### ball living room
# R,GOP16,GON5,GON4,GIN0,GON2,GIN12,GIN14,GIP13,GIP1
# 00: klingel
# 01: motion cellar
# 02: haustuer licht
# 04: aussen eck lichter
# 05: kronleuchter
# 12: gruppenschalter
# 13: motion ceiling
# 14: einzel licht schalter
# 16: led dimmer 
# -----------------------------------------------

light:
  - platform: mqtt ### LED dimmer
    name: "dev59"
    state_topic: "dev59/r/gpio_14_state"
    command_topic: "dev59/s/gpio_14_state"
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

# -----------------------------------------------

homeassistant:
  customize:
    light.dev59:
      friendly_name: "Basement"
    binary_sensor.dev59_motion:
      friendly_name: "Basement 1"
    binary_sensor.dev59_motion_2:
      friendly_name: "Basement 2"
    sensor.dev59_temperature:
      friendly_name: "59 Basement"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev59"
    fname: "59 Basement"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev59/r/gpio_13_state"
    name: "dev59_motion"
    device_class: motion

  - platform: mqtt
    state_topic: "dev59/r/gpio_16_state"
    name: "dev59_motion_2"
    device_class: motion

# -----------------------------------------------

