# -----------------------------------------------

homeassistant:
  customize:
    light.dev29:
      friendly_name: "Warm Water"
      retain: True
    binary_sensor.dev29_button:
      friendly_name: "Warm Water button"
    binary_sensor.dev29_button1s:
      friendly_name: "Warm Water button1s"
    binary_sensor.dev29_motion:
      friendly_name: "Warm Water motion"
      device_class: motion
    sensor.dev29_temperature:
      friendly_name: "Warm Water temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"
    switch.dev29_gpio_4:
      friendly_name: "Warm Water Emu"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev29"
    fname: "29 Warm Water"

# -----------------------------------------------
