### ball living room
# SL, DS18B20
# -----------------------------------------------

homeassistant:
  customize:
    light.dev12:
      friendly_name: "Hallway D"
      icon: "mdi:lamp"
    light.dev12_2:
      friendly_name: "Hallway D"
      icon: "mdi:lamp"
    light.dev12_simple_rainbow:
      icon: "mdi:traffic-light"
      friendly_name: "Hallway B1 Simple Rainbow"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev12"
    fname: "12 Hallway D B1"

# -----------------------------------------------

