# -----------------------------------------------

homeassistant:
  customize:
    light.dev32:
      friendly_name: "32 Bedroom Kolja"
      retain: True
    binary_sensor.dev32_button:
      friendly_name: "32 Bedroom Kolja button"
    binary_sensor.dev32_button1s:
      friendly_name: "32 Bedroom Kolja button1s"
    binary_sensor.dev32_motion:
      friendly_name: "32 Bedroom Kolja motion"
      device_class: motion
    sensor.dev32_temperature:
      friendly_name: "32 Bedroom Kolja temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev32"
    fname: "32 Bedroom Kolja"

# -----------------------------------------------
