# -----------------------------------------------

homeassistant:
  customize:
    light.dev2:
      friendly_name: "Donald"
      retain: True
    binary_sensor.dev2_button:
      friendly_name: "02 Donald button"
    binary_sensor.dev2_button1s:
      friendly_name: "02 Donald button1s"
    binary_sensor.dev2_motion:
      friendly_name: "02 Donald motion"
      device_class: motion
    sensor.dev2_temperature:
      friendly_name: "02 Donald temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev2"
    fname: "02 Donald"

# -----------------------------------------------
