# -----------------------------------------------

homeassistant:
  customize:
    light.dev25:
      friendly_name: "Beamer Shelly"
    binary_sensor.dev25_button:
      friendly_name: "Beamer Shelly button"
    binary_sensor.dev25_button1s:
      friendly_name: "Beamer Shelly button1s"
    binary_sensor.dev25_motion:
      friendly_name: "Beamer Shelly motion"
      device_class: motion
    sensor.dev25_temperature:
      friendly_name: "Beamer Shelly temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev25_adc:
      friendly_name: "Beamer Shelly"
    switch.dev25_gpio_4:
      friendly_name: "Beamer Sh Light"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev25"
    fname: "25 Beamer Shelly"

# -----------------------------------------------

input_boolean:
  approx_warn:
    name: "approximation warning"
    initial: off
