### ball living room
# SL
# -----------------------------------------------

light:
  - platform: mqtt ### bed room touch switch
    name: "dev3"
    state_topic: "dev3/r/light"
    command_topic: "dev3/s/light"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

# -----------------------------------------------

homeassistant:
  customize:
    light.dev3:
      friendly_name: "03 Kitchen Touch"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev3"
    fname: "03 Kitchen Touch"

# -----------------------------------------------


