# -----------------------------------------------

homeassistant:
  customize:
    light.dev34:
      friendly_name: "Spielecke Button"
    binary_sensor.dev34_button:
      friendly_name: "Spielecke Button button"
    binary_sensor.dev34_button1s:
      friendly_name: "Spielecke Button button1s"
    binary_sensor.dev34_motion:
      friendly_name: "Spielecke Button motion"
      device_class: motion
    sensor.dev34_temperature:
      friendly_name: "Spielecke Button temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev34_adc:
      friendly_name: "Spielecke Button"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev34"
    fname: "34 Spielecke Button"

# -----------------------------------------------
