### ball living room
# SL, DS18B20
# -----------------------------------------------

homeassistant:
  customize:
    light.dev56:
      friendly_name: "Lampinions carlo"
      retain: True
    binary_sensor.dev56_button:
      friendly_name: "Lampinions carlo button"
    binary_sensor.dev56_button1s:
      friendly_name: "Lampinions carlo button1s"
    binary_sensor.dev56_motion:
      friendly_name: "carlo motion"
      device_class: motion
    sensor.dev56_temperature:
      friendly_name: "Carlo"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev56"
    fname: "56 Lampinions carlo"


