# -----------------------------------------------

homeassistant:
  customize:
    light.dev28:
      friendly_name: "Workshop LED"
    binary_sensor.dev28_button:
      friendly_name: "Workshop button"
    binary_sensor.dev28_button1s:
      friendly_name: "Workshop button1s"
    binary_sensor.dev28_motion:
      friendly_name: "Workshop motion"
      device_class: motion
    sensor.dev28_temperature:
      friendly_name: "Workshop temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev28_adc:
      friendly_name: "Workshop"
    switch.dev28_gpio_4:
      friendly_name: "Workshop Air"
    switch.dev28_gpio_16:
      friendly_name: "Workshop Window 2"
    switch.dev28_gpio_15:
      friendly_name: "Workshop Vent"
    binary_sensor.dev28_countdown_state:
      friendly_name: "Workshop Vent countdown"
    switch.dev28_countdown:
      friendly_name: "Workshop Vent countdown"
    switch.dev28_countdown_l:
      friendly_name: "Workshop Vent long countdown"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev28"
    fname: "28 Workshop LED"

# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev28/r/countdown_state"
    name: "dev28_countdown_state"

switch:
  - platform: mqtt
    command_topic: "dev28/s/countdown"
    name: "dev28_countdown"
  - platform: mqtt
    command_topic: "dev28/s/countdown_l"
    name: "dev28_countdown_l"
