### ball living room
# SL, DS18B20
# -----------------------------------------------

homeassistant:
  customize:
    light.dev55:
      friendly_name: "Lampinions L."
      retain: True
    binary_sensor.dev55_button:
      friendly_name: "Lampinions L. button"
    binary_sensor.dev55_button1s:
      friendly_name: "Lampinions L. button1s"
    binary_sensor.dev55_motion:
      friendly_name: "L. motion"
      device_class: motion
    sensor.dev55_temperature:
      friendly_name: "L."
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev55"
    fname: "55 Lampinions L."


