# -----------------------------------------------

homeassistant:
  customize:
    light.dev3:
      friendly_name: "Kitchen Touch"
      retain: True
    binary_sensor.dev3_button:
      friendly_name: "Kitchen Touch button"
    binary_sensor.dev3_button1s:
      friendly_name: "Kitchen Touch button1s"
    binary_sensor.dev3_motion:
      friendly_name: "Kitchen Touch motion"
      device_class: motion
    sensor.dev3_temperature:
      friendly_name: "Kitchen Touch temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev3"
    fname: "03 Kitchen Touch"

# -----------------------------------------------
