### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### LED H801
    name: "dev19"
    state_topic: "dev19/r/light"
    command_topic: "dev19/s/light/dimm"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev19:
      friendly_name: "Workshop LED"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev19"
    fname: "19 Workshop LED"

# -----------------------------------------------
