### ball living room
# R,GOP16,GON5,GON4,GIN0,GON2,GIN12,GIN14,GIP13,GIP1
# 00: klingel
# 01: motion cellar
# 02: haustuer licht
# 04: aussen eck lichter
# 05: kronleuchter
# 12: gruppenschalter
# 13: motion ceiling
# 14: einzel licht schalter
# 16: led dimmer 
# -----------------------------------------------

light:
  - platform: mqtt ### LED dimmer
    name: "dev54"
    state_topic: "dev54/r/gpio_16_state"
    command_topic: "dev54/s/gpio_16_dimm"
    brightness_state_topic: 'dev54/r/gpio_16_brightness'
    brightness_command_topic: 'dev54/s/gpio_16_brightness'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

  - platform: mqtt ### kronleuchter
    name: "dev54_2"
    state_topic: "dev54/r/gpio_5_state"
    command_topic: "dev54/s/gpio_5_dimm"
    brightness_state_topic: 'dev54/r/gpio_5_brightness'
    brightness_command_topic: 'dev54/s/gpio_5_brightness'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

  - platform: mqtt ### aussen-ecken-licht
    name: "dev54_3"
    command_topic: "dev54/s/gpio_4_state"
    state_topic: "dev54/r/gpio_4_state"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

  - platform: mqtt ### aussenlicht haustuer
    name: "dev54_4"
    command_topic: "dev54/s/gpio_2_state"
    state_topic: "dev54/r/gpio_2_state"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

homeassistant:
  customize:
    switch.dev54_gpio_2:
      friendly_name: "Main Door light"
    switch.dev54_gpio_4:
      friendly_name: "House Exterior light"
    switch.dev54_gpio_5:
      friendly_name: "Chandelier Foyer"
    switch.dev54_gpio_16:
      friendly_name: "LED Foyer"
    light.dev54:
      friendly_name: "LED Foyer"
    light.dev54_2:
      friendly_name: "Chandelier Foyer"
    light.dev54_3:
      friendly_name: "House Exterior light"
    light.dev54_4:
      friendly_name: "Main Door light"
    binary_sensor.dev54_motion_1:
      friendly_name: "54_1 Foyer ceiling"
    binary_sensor.dev54_motion_2:
      friendly_name: "54_2 Foyer cellar"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev54"
    fname: "54 Ultra Foyer"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev54/r/gpio_13_state"
    name: "dev54_motion_1"
    device_class: motion
  - platform: mqtt
    state_topic: "dev54/r/gpio_1_state"
    name: "dev54_motion_2"
    device_class: motion

# -----------------------------------------------

automation:
#------- Toggle LED -----------
  - alias: Toggle_Foyer_LED_by_switch
    initial_state: True
    trigger:
      - platform: mqtt
        topic: "dev54/r/gpio_14_hold"
        payload: "1"
    action:
      - service: light.toggle
        entity_id: light.dev54
#------- Toggle Chandelier -----------
  - alias: Toggle_Foyer_chanelier_by_switch
    initial_state: True
    trigger:
      - platform: mqtt
        topic: "dev54/r/gpio_14_hold"
        payload: "2"
    action:
      - service: light.toggle
        entity_id: light.dev54_2

# -----------------------------------------------

script:
  seq_dingdong:
    sequence:
      - service: notify.pb
        data:
          title: "Doorbell"
          message: "Ding Dong"

      - service: notify.pb_c
        data:
          title: "Doorbell"
          message: "Ding Dong"

      - service: shell_command.camxia2_1

      - service: notify.pb 
        data:
          title: "Doorbell"
          message: "cam 2"
          data:
            file: /tmp/xia2_1.jpg

      - service: notify.pb_c
        data:
          title: "Doorbell"
          message: "cam 2"
          data:
            file: /tmp/xia2_1.jpg

# -----------------------------------------------
