# -----------------------------------------------

homeassistant:
  customize:
    light.dev6:
      friendly_name: "Cellar"
      retain: True
    binary_sensor.dev6_button:
      friendly_name: "Cellar button"
    binary_sensor.dev6_button1s:
      friendly_name: "Cellar button1s"
    binary_sensor.dev6_motion:
      friendly_name: "Cellar motion"
      device_class: motion
    sensor.dev6_temperature:
      friendly_name: "Cellar temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev6"
    fname: "06 Cellar"

# -----------------------------------------------
