# -----------------------------------------------

homeassistant:
  customize:
    light.dev11:
      friendly_name: "Tower R"
      retain: True
    binary_sensor.dev11_button:
      friendly_name: "Tower R button"
    binary_sensor.dev11_button1s:
      friendly_name: "Tower R button1s"
    binary_sensor.dev11_motion:
      friendly_name: "Tower R motion"
      device_class: motion
    sensor.dev11_temperature:
      friendly_name: "Tower R temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev11"
    fname: "11 Tower R"

# -----------------------------------------------
