
homeassistant:
  customize:
    switch.dev41_gpio_4:
      friendly_name: "WW Heater 1"
      icon: mdi:fire
    switch.dev41_gpio_5:
      friendly_name: "WW Heater 2"
      icon: mdi:fire
    switch.dev41_gpio_12:
      friendly_name: "WW Heater 3"
      icon: mdi:fire
    switch.dev41_gpio_15:
      friendly_name: "WW Heater 4"
      icon: mdi:fire
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev41"
    fname: "41 WW Heater"

  - platform: history_stats
    name: WW1
    entity_id: switch.dev41_gpio_4
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: WW2
    entity_id: switch.dev41_gpio_5
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

  - platform: history_stats
    name: WW3
    entity_id: switch.dev41_gpio_12
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'
# -----------------------------------------------
