# -----------------------------------------------

homeassistant:
  customize:
    light.dev16:
      friendly_name: "EM"
    binary_sensor.dev16_button:
      friendly_name: "EM button"
    binary_sensor.dev16_button1s:
      friendly_name: "EM button1s"
    binary_sensor.dev16_motion:
      friendly_name: "EM motion"
      device_class: motion
    sensor.dev16_temperature:
      friendly_name: "EM temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev16_adc:
      friendly_name: "EM"
    sensor.dev16_em_cur:
      friendly_name: "EM current"
      unit_of_measurement: "W"
    sensor.dev16_em_tot:
      friendly_name: "EM total"
      unit_of_measurement: "kWh"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev16"
    fname: "16 EM"

# -----------------------------------------------
