### ball living room
# SL, DS18B20
# -----------------------------------------------

homeassistant:
  customize:
    light.dev42:
      friendly_name: "Hallway D2"
      icon: "mdi:lamp"
    light.dev42_2:
      friendly_name: "Hallway D2"
      icon: "mdi:lamp"
    light.dev42_simple_rainbow:
      icon: "mdi:traffic-light"
      friendly_name: "Hallway B1 Simple Rainbow2"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev42"
    fname: "42 Hallway D B1"

# -----------------------------------------------

