# -----------------------------------------------

homeassistant:
  customize:
    light.dev4:
      friendly_name: "Basement 4CH"
    binary_sensor.dev4_button:
      friendly_name: "Basement 4CH button"
    binary_sensor.dev4_button1s:
      friendly_name: "Basement 4CH button1s"
    binary_sensor.dev4_motion:
      friendly_name: "Basement 4CH motion"
      device_class: motion
    sensor.dev4_temperature:
      friendly_name: "Basement 4CH temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev4_humidity:
      friendly_name: "Basement 4CH humidity"
      unit_of_measurement: "%"
      icon: "mdi:water-percent"
      device_class: "humidity"
    sensor.dev4_adc:
      friendly_name: "Basement 4CH"
    switch.dev4_gpio_4:
      friendly_name: "Dryroom relais X"
    switch.dev4_gpio_13:
      friendly_name: "Dryroom relais X"
    switch.dev4_gpio_15:
      friendly_name: "Dryroom relais X"
    switch.dev4_gpio_5:
      friendly_name: "Dryroom vent"
    switch.dev4_gpio_12:
      friendly_name: "Water pump"
      icon: mdi:water-pump
    switch.dev4_gpio_12_autostart:
      friendly_name: "Water Auto"
      icon: mdi:water-pump

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev4"
    fname: "04 Basement 4CH"

  - platform: statistics_jkw
    entity_id: sensor.dev4_humidity
    name: dev4_humidity_stat
    sampling_size: 40

  - platform: template
    sensors:
      dev4_hum_der:
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.dev4_humidity_stat', 'averaged_derivation') }}"
# -----------------------------------------------
switch:
  - platform: mqtt ### autostart fakesensor
    name: "dev4_gpio_12_autostart"
    command_topic: "dev14/s/light_autostart"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

