# -----------------------------------------------

homeassistant:
  customize:
    light.dev37:
      friendly_name: "EM"
    binary_sensor.dev37_button:
      friendly_name: "EM button"
    binary_sensor.dev37_button1s:
      friendly_name: "EM button1s"
    binary_sensor.dev37_motion:
      friendly_name: "EM motion"
      device_class: motion
    sensor.dev37_temperature:
      friendly_name: "EM temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev37_adc:
      friendly_name: "EM"
    sensor.dev37_em_cur:
      friendly_name: "EM current"
      unit_of_measurement: "W"
    sensor.dev37_em_cur_l1:
      friendly_name: "EM current L1"
      unit_of_measurement: "W"
    sensor.dev37_em_cur_l2:
      friendly_name: "EM current L2"
      unit_of_measurement: "W"
    sensor.dev37_em_cur_l3:
      friendly_name: "EM current L3"
      unit_of_measurement: "W"
    sensor.dev37_em_tot:
      friendly_name: "EM total"
      unit_of_measurement: "kWh"
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev37"
    fname: "37 EM"

# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev37/r/energy_cost"
    name: "energy_cost"
# -----------------------------------------------

