### kitchen hood
# SL, Ds18b20
# -----------------------------------------------
light:
  - platform: mqtt ### 
    name: "dev2"
    state_topic: "dev2/r/light"
    command_topic: "dev2/s/light"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

# -----------------------------------------------

homeassistant:
  customize:
    light.dev2:
      friendly_name: "Donald"
      icon: "mdi:lamp"
    sensor.dev2_temperature:
      friendly_name: "Donald"
      icon: "mdi:thermometer"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev2"
    fname: "02 Donald"

  - platform: mqtt
    state_topic: "dev2/r/temperature"
    name: "dev2_temperature"
    unit_of_measurement: "ºC"

# -----------------------------------------------


