### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ###  lampinions flur oben
    name: "dev55"
    state_topic: "dev55/r/light"
    command_topic: "dev55/s/light/dimm"
    brightness_state_topic: 'dev55/r/light/brightness'
    brightness_command_topic: 'dev55/s/light/brightness'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev55:
      friendly_name: "Lampinions carlo"
      retain: True
    binary_sensor.dev55_button:
      friendly_name: "Lampinions carlo button"
    binary_sensor.dev55_button1s:
      friendly_name: "Lampinions carlo button1s"
    binary_sensor.dev55_motion:
      friendly_name: "carlo motion"
      device_class: motion
    sensor.dev55_temperature:
      friendly_name: "Carlo"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev55"
    fname: "55 Lampinions carlo"


