### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### LED H801
    name: "dev18"
    state_topic: "dev18/r/light"
    command_topic: "dev18/s/light/dimm"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev18:
      friendly_name: "PI"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev18"
    fname: "18 PI"

# -----------------------------------------------
