
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev23"
    fname: "23 Carlo"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev23:
      friendly_name: "Carlo"

