### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### tower dinning
    name: "dev7"
    command_topic: "dev7/s/light"
    state_topic: "dev7/r/light"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev7:
      friendly_name: "TowerW"
      icon: "mdi:lamp"
    sensor.dev7_temperature:
      friendly_name: "TowerW"
      icon: "mdi:thermometer"
    binary_sensor.dev7_motion:
      friendly_name: "TowerW"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev7"
    fname: "07 TowerW"

  - platform: mqtt
    state_topic: "dev7/r/temperature"
    name: "dev7_temperature"
    unit_of_measurement: "ºC"

# -----------------------------------------------


