# -----------------------------------------------

homeassistant:
  customize:
    light.dev29:
      friendly_name: "Warm Water"
      retain: True
    binary_sensor.dev29_button:
      friendly_name: "Warm Water button"
    binary_sensor.dev29_button1s:
      friendly_name: "Warm Water button1s"
    binary_sensor.dev29_motion:
      friendly_name: "Warm Water motion"
      device_class: motion
    sensor.dev29_temperature:
      friendly_name: "Warm Water temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    switch.dev29_gpio_4:
      friendly_name: "Warm Water Emu"
    binary_sensor.dev29_gpio_5:
      friendly_name: "Heater Error"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev29"
    fname: "29 Warm Water"

  - platform: statistics_jkw
    entity_id: sensor.dev29_temperature
    name: dev29_temperature_stat
    sampling_size: 10

  - platform: template
    sensors:
      dev29_temperature_der:
        unit_of_measurement: "%"
        value_template: "{{ state_attr('sensor.dev29_temperature_stat_mean', 'averaged_derivation') }}"

# -----------------------------------------------
