### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ###  lampinions flur oben
    name: "dev55"
    state_topic: "dev55/r/light"
    command_topic: "dev55/s/light/dimm"
    brightness_state_topic: 'dev55/r/light/brightness'
    brightness_command_topic: 'dev55/s/light/brightness'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev55:
      friendly_name: "Lampinions carlo"
    sensor.dev55_temperature:
      friendly_name: "Carlo"
      icon: "mdi:thermometer"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev55"
    fname: "55 Lampinions carlo"

  - platform: mqtt
    state_topic: "dev55/r/temperature"
    name: "dev55_temperature"
    unit_of_measurement: "ºC"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev55/r/gpio_13_state"
    name: "dev55_motion"
    device_class: motion

