# -----------------------------------------------

homeassistant:
  customize:
    light.dev20:
      friendly_name: "Workshop"
      retain: True
    binary_sensor.dev20_button:
      friendly_name: "Workshop button"
    binary_sensor.dev20_button1s:
      friendly_name: "Workshop button1s"
    binary_sensor.dev20_motion:
      friendly_name: "Workshop motion"
      device_class: motion
    sensor.dev20_temperature:
      friendly_name: "Workshop temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev20"
    fname: "20 Workshop"

# -----------------------------------------------
