# -----------------------------------------------

homeassistant:
  customize:
    light.dev36:
      friendly_name: "Pillar"
    binary_sensor.dev36_button:
      friendly_name: "Pillar button"
    binary_sensor.dev36_button1s:
      friendly_name: "Pillar button1s"
    binary_sensor.dev36_motion:
      friendly_name: "Pillar motion"
      device_class: motion
    sensor.dev36_temperature:
      friendly_name: "Pillar temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev36_adc:
      friendly_name: "Pillar"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev36"
    fname: "36 Pillar"

# -----------------------------------------------
