### touch bedroom
# SL
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev23"
    fname: "23 Bedroom Touch"

  - platform: mqtt
    state_topic: "dev23/r/gpio_0_hold"
    name: "dev23_0_hold"

# -----------------------------------------------

homeassistant:
  customize:
    switch.dev23:
      friendly_name: "Bed Ventilator"
      icon: "mdi:fan"

