# -----------------------------------------------

homeassistant:
  customize:
    light.dev13:
      friendly_name: "Leakage"
      retain: True
    binary_sensor.dev13_button:
      friendly_name: "Leakage button"
    binary_sensor.dev13_button1s:
      friendly_name: "Leakage button1s"
    binary_sensor.dev13_motion:
      friendly_name: "Leakage motion"
      device_class: motion
    sensor.dev13_temperature:
      friendly_name: "Leakage temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev13_adc:
      friendly_name: "Leakage"
      unit_of_measurement: "°C"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev13"
    fname: "13 Leakage"

# -----------------------------------------------
