### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### b1
    name: "dev27"
    state_topic: "dev27/r/light"
    command_topic: "dev27/s/light/dimm"
    rgb_state_topic: 'dev27/r/light/dimm/color'
    rgb_command_topic: 'dev27/s/light/dimm/color'
    brightness_state_topic: 'dev27/r/light/brightness'
    brightness_command_topic: 'dev27/s/light/brightness'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99
  - platform: mqtt ### b1
    name: "dev27_simple_rainbow"
    state_topic: "dev27/r/light/animation/simple_rainbow"
    command_topic: "dev27/s/light/animation/simple_rainbow"
    retain: True
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev27:
      friendly_name: "UpStairs"
      retain: True
      icon: "mdi:lamp"
    binary_sensor.dev27_button:
      friendly_name: "UpStairs button"
    binary_sensor.dev27_button1s:
      friendly_name: "UpStairs button1s"
    binary_sensor.dev27_motion:
      friendly_name: "UpStairs motion"
      device_class: motion
    sensor.dev27_temperature:
      friendly_name: "UpStairs temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
      
    light.dev27_simple_rainbow:
      icon: "mdi:traffic-light"
      friendly_name: "27 UpStairs Rain"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev27"
    fname: "27 B1"
    
  - platform: mqtt
    state_topic: "dev27/r/uptime"
    name: "dev27_uptime"
    unit_of_measurement: "min"

# -----------------------------------------------


