# -----------------------------------------------

homeassistant:
  customize:
    light.dev1:
      friendly_name: "Ball"
      retain: True
    binary_sensor.dev1_button:
      friendly_name: "Ball button"
    binary_sensor.dev1_button1s:
      friendly_name: "Ball button1s"
    binary_sensor.dev1_motion:
      friendly_name: "Ball motion"
      device_class: motion
    sensor.dev1_temperature:
      friendly_name: "Ball temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev1"
    fname: "01 Ball"

# -----------------------------------------------
