# -----------------------------------------------

homeassistant:
  customize:
    light.dev58:
      friendly_name: "MediaPC"
    binary_sensor.dev58_button:
      friendly_name: "MediaPC button"
    binary_sensor.dev58_button1s:
      friendly_name: "MediaPC button1s"
    binary_sensor.dev58_motion:
      friendly_name: "MediaPC motion"
      device_class: motion
    sensor.dev58_temperature:
      friendly_name: "MediaPC temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev58_adc:
      friendly_name: "MediaPC"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev58"
    fname: "58 MediaPC"

# -----------------------------------------------
