# -----------------------------------------------

homeassistant:
  customize:
    light.dev17:
      friendly_name: "BaseDoor"
    binary_sensor.dev17_button:
      friendly_name: "BaseDoor button"
    binary_sensor.dev17_button1s:
      friendly_name: "BaseDoor button1s"
    binary_sensor.dev17_motion:
      friendly_name: "BaseDoor motion"
      device_class: motion
    sensor.dev17_temperature:
      friendly_name: "BaseDoor temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev17_adc:
      friendly_name: "BaseDoor"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev17"
    fname: "17 BaseDoor"

# -----------------------------------------------
binary_sensor:
  - platform: mqtt
    state_topic: "dev17/r/gpio_5_state"
    name: "dev17_motion"
    device_class: motion
    payload_on: "OFF"
    payload_off: "ON"
