# -----------------------------------------------

homeassistant:
  customize:
    light.dev60:
      friendly_name: "Beamer"
    binary_sensor.dev60_button:
      friendly_name: "Beamer button"
    binary_sensor.dev60_button1s:
      friendly_name: "Beamer button1s"
    binary_sensor.dev60_motion:
      friendly_name: "Beamer motion"
      device_class: motion
    sensor.dev60_temperature:
      friendly_name: "Beamer temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    switch.dev60_gpio_13:
      friendly_name: "Window"
      icon: "mdi:door-open"
    switch.dev60_gpio_12:
      friendly_name: "Vent"
      icon: "mdi:air-filter"
    sensor.dev60_adc:
      friendly_name: "Beamer"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev60"
    fname: "60 Beamer"

# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev60/r/countdown_state"
    name: "dev60_countdown_state"

switch:
  - platform: mqtt
    command_topic: "dev60/s/countdown"
    name: "dev60_countdown"
