# -----------------------------------------------

homeassistant:
  customize:
    light.dev99:
      friendly_name: "99 testing"
      retain: True
    binary_sensor.dev99_motion:
      friendly_name: "99 testing motion"
      device_class: motion
    sensor.dev99_temperature:
      friendly_name: "99 testing temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev99"
    fname: "99 testing"

# -----------------------------------------------
