### ball living room
# SL
# -----------------------------------------------

light:
  - platform: mqtt ### steckdosen dings Water pumpe
    name: "dev17"
    state_topic: "dev17/r/light"
    command_topic: "dev17/s/light"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

  - platform: mqtt ### steckdosen dings Water pumpe
    name: "dev17_30"
    state_topic: "dev17/r/light"
    command_topic: "dev17/s/light"
    qos: 0
    retain: True
    payload_on: "ONFOR1800"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

  - platform: mqtt ### steckdosen dings Water pumpe
    name: "dev17_45"
    state_topic: "dev17/r/light"
    command_topic: "dev17/s/light"
    qos: 0
    retain: True
    payload_on: "ONFOR2700"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

  - platform: mqtt ### autostart fakesensor
    name: "dev17_autostart"
    command_topic: "dev17/s/light_autostart"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"



# -----------------------------------------------

homeassistant:
  customize:
    light.dev17:
      friendly_name: "Water pump"
      icon: mdi:water-pump

    light.dev17_autostart:
      friendly_name: "Water Auto"
      icon: mdi:water-pump

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev17"
    fname: "17 Water pump"

# -----------------------------------------------

automation:
  - alias: pump_off
    initial_state: True
    hide_entity: False
    trigger:
      - platform: mqtt
        topic: irrigation
        payload: 'off'
    action:
      - service: light.turn_off
        entity_id: light.dev17


# -----------------------------------------------

