# -----------------------------------------------

homeassistant:
  customize:
    light.dev26:
      friendly_name: "BBedroom"
    binary_sensor.dev26_button:
      friendly_name: "BBedroom button"
    binary_sensor.dev26_button1s:
      friendly_name: "BBedroom button1s"
    binary_sensor.dev26_motion:
      friendly_name: "BBedroom motion"
      device_class: motion
    sensor.dev26_temperature:
      friendly_name: "BBedroom temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev26_adc:
      friendly_name: "BBedroom"
    switch.dev26_gpio_15:
      friendly_name: "BB Ventilator"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev26"
    fname: "26 BBedroom"

  - platform: mqtt
    state_topic: "dev26/r/gpio_5_hold"
    name: "dev26_5_hold"

# -----------------------------------------------

