### ball living room
# SL, DS18B20
# -----------------------------------------------

homeassistant:
  customize:
    light.dev15:
      friendly_name: "Worldmap"
      retain: True
    binary_sensor.dev15_button:
      friendly_name: "Worldmap button"
    binary_sensor.dev15_button1s:
      friendly_name: "Worldmap button1s"
    binary_sensor.dev15_motion:
      friendly_name: "Worldmap motion"
      device_class: motion
    sensor.dev15_temperature:
      friendly_name: "Worldmap temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev15"
    fname: "15 Worldmap"
    
  - platform: mqtt
    state_topic: "dev15/r/uptime"
    name: "dev15_uptime"
    unit_of_measurement: "min"

# -----------------------------------------------


