### valve ctrl
# 4x water valve
# -----------------------------------------------

### valve power "dev30/s/gpio_2_state"
### valve 1 "dev30/s/gpio_16_state"
### valve 2 "dev30/s/gpio_4_state"
### valve 3 "dev30/s/gpio_5_state"
### valve 4 "dev30/s/gpio_15_state"
### valve 5 "dev30/s/gpio_14_state"


switch:
  - platform: mqtt ### reset raintime
    name: "dev30_reset_rain_time"
    command_topic: "dev30/s/uptime_reset"
    state_topic: "dev30/r/uptime_reset"
    qos: 0
    retain: True
    payload_on: "now"
    payload_off: "OFF"


# -----------------------------------------------


homeassistant:
  customize:
    switch.dev30_gpio_16:
      friendly_name: "Valve LT Lounge"
      icon: mdi:call-split
    switch.dev30_gpio_0:
      friendly_name: "Pool pump"
      icon: mdi:water-pump
    switch.dev30_gpio_4:
      friendly_name: "Valve 3xT200"
      icon: mdi:call-split
    switch.dev30_gpio_5:
      friendly_name: "Valve LT Pool"
      icon: mdi:call-split
    switch.dev30_gpio_15:
      friendly_name: "Valve 2xT200"
      icon: mdi:call-split
    switch.dev30_gpio_14:
      friendly_name: "Valve vegetable"
      icon: mdi:call-split
    switch.dev30_gpio_2:
      friendly_name: "Water valve Power"
      icon: mdi:power-plug
    sensor.dev30_uptime:
      friendly_name: "Rain time today"
      icon: mdi:clock-start
    sensor.dev30_state:
      friendly_name: "Irrigation state"
      icon: mdi:access-point
    sensor.dev30_temperature:
      friendly_name: "Pool temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev30"
    fname: "30 Water valve"
  - platform: mqtt
    state_topic: "dev30/r/uptime"
    name: "dev30_uptime"
    unit_of_measurement: "min"
  - platform: mqtt
    state_topic: "dev30/r/state"
    name: "dev30_state"
#  - platform: mqtt
#    state_topic: "dev30_pumptime"
#    name: "dev30_pumptime"
#    unit_of_measurement: "min"
  - platform: history_stats
    name: pump_time
    entity_id: switch.dev30_gpio_0
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0, minute=0, second=0) }}'
    end: '{{ now() }}'

# -----------------------------------------------

input_boolean:
  irrigation:
    name: "Irrigation"
    initial: off
    icon: mdi:basket-fill
  irrigation_override:
    name: "Force Irrigation"
    initial: off
    icon: mdi:basket-fill

# -----------------------------------------------

