# -----------------------------------------------

homeassistant:
  customize:
    light.dev31:
      friendly_name: "31 Bedroom Caro"
      retain: True
    binary_sensor.dev31_button:
      friendly_name: "31 Bedroom Caro button"
    binary_sensor.dev31_button1s:
      friendly_name: "31 Bedroom Caro button1s"
    binary_sensor.dev31_button3s:
      friendly_name: "31 Bedroom Caro button3s"
    binary_sensor.dev31_motion:
      friendly_name: "31 Bedroom Caro motion"
      device_class: motion
    sensor.dev31_temperature:
      friendly_name: "31 Bedroom Caro temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev31"
    fname: "31 Bedroom Caro"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev31/r/button3s"
    name: "dev31_button3s"

# -----------------------------------------------
