# -----------------------------------------------

homeassistant:
  customize:
    light.dev16:
      friendly_name: "ADS"
    binary_sensor.dev16_button:
      friendly_name: "ADS button"
    binary_sensor.dev16_button1s:
      friendly_name: "ADS button1s"
    binary_sensor.dev16_motion:
      friendly_name: "ADS motion"
      device_class: motion
    sensor.dev16_tADSperature:
      friendly_name: "ADS tADSperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "tADSperature"
    sensor.dev16_adc:
      friendly_name: "ADS"
    sensor.dev16_ADS_cur:
      friendly_name: "ADS current"
      unit_of_measurement: "W"
    sensor.dev16_ADS_cur_l1:
      friendly_name: "ADS current L1"
      unit_of_measurement: "W"
    sensor.dev16_ADS_cur_l2:
      friendly_name: "ADS current L2"
      unit_of_measurement: "W"
    sensor.dev16_ADS_cur_l3:
      friendly_name: "ADS current L3"
      unit_of_measurement: "W"
    sensor.dev16_ADS_tot:
      friendly_name: "ADS total"
      unit_of_measurement: "kWh"
    sensor.dev16_ads_ch0:
      friendly_name: "ADS CH0"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch1:
      friendly_name: "ADS CH1"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch2:
      friendly_name: "ADS CH2"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch3:
      friendly_name: "ADS CH3"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch4:
      friendly_name: "ADS CH4"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch5:
      friendly_name: "ADS CH5"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch6:
      friendly_name: "ADS CH6"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch7:
      friendly_name: "ADS CH7"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch8:
      friendly_name: "ADS CH8"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch9:
      friendly_name: "ADS CH9"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch10:
      friendly_name: "ADS CH10"
      unit_of_measurement: "mV"
    sensor.dev16_ads_ch11:
      friendly_name: "ADS CH11"
      unit_of_measurement: "mV"
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev16"
    fname: "16 ADS"

# -------------- fake sensors for appdeamon ---------------

  - platform: mqtt
    state_topic: "dev16/r/energy_cost"
    name: "energy_cost"
# -----------------------------------------------

  - platform: template
    sensors: 
        dev16_ads_ch0_kw: 
           friendly_name: "00 Washing Machine"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch0')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch1_kw: 
           friendly_name: "01 Garden drain pump"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch1')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch2_kw: 
           friendly_name: "02 House drain pump + Beamer"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch2')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch3_kw: 
           friendly_name: "03 Pool pump + WW Heater"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch3')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch4_kw: 
           friendly_name: "04 ADS CH4"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch4')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch5_kw: 
           friendly_name: "05 ADS CH5"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch5')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch6_kw: 
           friendly_name: "06 ADS CH6"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch6')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch7_kw: 
           friendly_name: "07 Ref measurement"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch7')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch8_kw: 
           friendly_name: "08 Garage Back"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch8')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch9_kw: 
           friendly_name: "09 C. Office, Hallway"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch9')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch10_kw: 
           friendly_name: "10 C. Bath, Supply"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch10')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
        dev16_ads_ch11_kw: 
           friendly_name: "11 Pool Heater"
           unit_of_measurement: 'W'
           value_template: "{{ [(((states('sensor.dev16_ads_ch11')|float)-(states('sensor.dev16_ads_ch7')|float)) * 0.66) | round(2), 0.00] | max }}"
