### kronleuchter kueche
# R,BS5,SL4
# -----------------------------------------------

light:
  - platform: mqtt ### bed room touch switch
    name: "dev5"
    state_topic: "dev5/r/light"
    command_topic: "dev5/s/light"
    qos: 0
    retain: True
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false

# -----------------------------------------------

homeassistant:
  customize:
    light.dev5:
      friendly_name: "05 Kitchen Kronleuchter"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev5"
    fname: "05 Kitchen Kronleuchter"

  - platform: mqtt
    state_topic: "dev5/r/button"
    name: "dev5_button"

# -----------------------------------------------


