### ball living room
# R,GOP16,GON5,GON4,GIN0,GON2,GIN12,GIN14,GIP13,GIP1
# 00: klingel
# 01: motion cellar
# 02: haustuer licht
# 04: aussen eck lichter
# 05: kronleuchter
# 12: gruppenschalter
# 13: motion ceiling
# 14: einzel licht schalter
# 16: led dimmer 
# -----------------------------------------------

homeassistant:
  customize:
    light.dev59:
      friendly_name: "Basement"
    binary_sensor.dev59_motion_13:
      friendly_name: "Basement 1"
      device_class: "motion"
    binary_sensor.dev59_motion_16:
      friendly_name: "Basement 2"
      device_class: "motion"
    sensor.dev59_temperature:
      friendly_name: "59 Basement"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev59"
    fname: "59 Basement"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "dev59/r/gpio_13_state"
    name: "dev59_motion_13"
    device_class: motion

  - platform: mqtt
    state_topic: "dev59/r/gpio_16_state"
    name: "dev59_motion_16"
    device_class: motion

# -----------------------------------------------

