# -----------------------------------------------

homeassistant:
  customize:
    light.dev14:
      friendly_name: "Fridge"
      retain: True
    binary_sensor.dev14_button:
      friendly_name: "Fridge button"
    binary_sensor.dev14_button14s:
      friendly_name: "Fridge button1s"
    binary_sensor.dev14_motion:
      friendly_name: "Fridge motion"
      device_class: motion
    sensor.dev14_temperature:
      friendly_name: "Fridge temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev14"
    fname: "14 Fridge"

# -----------------------------------------------
