# -----------------------------------------------

homeassistant:
  customize:
    light.dev19:
      friendly_name: "Workshop LED"
    binary_sensor.dev19_button:
      friendly_name: "Workshop LED button"
    binary_sensor.dev19_button1s:
      friendly_name: "Workshop LED button1s"
    binary_sensor.dev19_motion:
      friendly_name: "Workshop LED motion"
      device_class: motion
    sensor.dev19_temperature:
      friendly_name: "Workshop LED temperature"
      unit_of_measurement: "ºC"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev19_adc:
      friendly_name: "Workshop LED"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev19"
    fname: "19 Workshop LED"

# -----------------------------------------------
