### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### cam illumino 101
    name: "dev101"
    state_topic: "128480595098010/r/light"
    command_topic: "128480595098010/s/light/dimm"
    rgb_state_topic: '128480595098010/r/light/dimm/color'
    rgb_command_topic: '128480595098010/s/light/dimm/color'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev101:
      friendly_name: "Couch C"
    binary_sensor.dev101_motion:
      friendly_name: "Couch C"
    camera.cam_101:
      friendly_name: "Couch"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "128480595098010/r/motion"
    name: "dev101_motion"
    device_class: motion

# -----------------------------------------------

camera:
  - name: cam_101
    platform: generic
    still_image_url: http://192.168.2.101/cam_full.jpg

# -----------------------------------------------

shell_command:
  cam1_1: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_1.jpg
  cam1_2: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_2.jpg
  cam1_3: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_3.jpg
  cam1_4: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_4.jpg
  cam1_5: wget http://192.168.2.101/cam_full.jpg -O /tmp/101_5.jpg

# -----------------------------------------------

script:
  seq_101:
    sequence:
      - service: script.update_location
      - service: shell_command.cam1_1
      - delay:
          seconds: 2
      - service: shell_command.cam1_2
      - delay:
          seconds: 2
      - service: shell_command.cam1_3
      - delay:
          seconds: 2
      - service: shell_command.cam1_4
      - delay:
          seconds: 2
      - service: shell_command.cam1_5
      - condition: state # check that still noone came home with the last 10 sec
        entity_id: binary_sensor.someone_is_home
        state: 'off'
      - service: notify.pb 
        data:
          title: "Cam 1 pic 01"
          message: "motion"
          data:
            file: /tmp/101_1.jpg
      - service: notify.pb 
        data:
          title: "Cam 1 pic 02"
          message: "motion"
          data:
            file: /tmp/101_2.jpg
      - service: notify.pb 
        data:
          title: "Cam 1 pic 03"
          message: "motion"
          data:
            file: /tmp/101_3.jpg
      - service: notify.pb 
        data:
          title: "Cam 1 pic 04"
          message: "motion"
          data:
            file: /tmp/101_4.jpg
      - service: notify.pb 
        data:
          title: "Cam 1 pic 05"
          message: "motion"
          data:
            file: /tmp/101_5.jpg

