### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### cam illumino 103
    name: "dev103"
    state_topic: "128480595098001/r/light"
    command_topic: "128480595098001/s/light/dimm"
    rgb_state_topic: '128480595098001/r/light/dimm/color'
    rgb_command_topic: '128480595098001/s/light/dimm/color'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev103:
      friendly_name: "TV C"
    binary_sensor.dev103_motion:
      friendly_name: "TV C"
    camera.cam_103:
      friendly_name: "TV"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "128480595098001/r/motion"
    name: "dev103_motion"
    device_class: motion

# -----------------------------------------------

script:
  seq_103:
    sequence:
      - service: script.update_location
      - service: shell_command.cam3_1
      - delay:
          seconds: 2
      - service: shell_command.cam3_2
      - delay:
          seconds: 2
      - service: shell_command.cam3_3
      - delay:
          seconds: 2
      - service: shell_command.cam3_4
      - delay:
          seconds: 2
      - service: shell_command.cam3_5
      - condition: state # check that still noone came home with the last 10 sec
        entity_id: binary_sensor.someone_is_home
        state: 'off'
      - service: notify.pb 
        data:
          title: "Cam 3 pic 01"
          message: "motion"
          data:
            file: /tmp/103_1.jpg
      - service: notify.pb 
        data:
          title: "Cam 3 pic 02"
          message: "motion"
          data:
            file: /tmp/103_2.jpg
      - service: notify.pb 
        data:
          title: "Cam 3 pic 03"
          message: "motion"
          data:
            file: /tmp/103_3.jpg
      - service: notify.pb 
        data:
          title: "Cam 3 pic 04"
          message: "motion"
          data:
            file: /tmp/103_4.jpg
      - service: notify.pb 
        data:
          title: "Cam 3 pic 05"
          message: "motion"
          data:
            file: /tmp/103_5.jpg

