### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### cam illumino 106
    name: "dev106"
    state_topic: "137291054495417/r/light"
    command_topic: "137291054495417/s/light/dimm"
    rgb_state_topic: '137291054495417/r/light/dimm/color'
    rgb_command_topic: '137291054495417/s/light/dimm/color'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev106:
      friendly_name: "Dragonfly C"
    binary_sensor.dev106_motion:
      friendly_name: "Dragonfly C"
    camera.cam_106:
      friendly_name: "Dragonfly"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "137291054495417/r/motion"
    name: "dev106_motion"
    device_class: motion

# -----------------------------------------------

camera:
  - name: cam_106
    platform: generic
    still_image_url: http://192.168.2.106/cam_full.jpg

# -----------------------------------------------

shell_command:    
  cam6_1: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_1.jpg
  cam6_2: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_2.jpg
  cam6_3: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_3.jpg
  cam6_4: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_4.jpg
  cam6_5: wget http://192.168.2.106/cam_full.jpg -O /tmp/106_5.jpg

# -----------------------------------------------

script:
  seq_106:
    sequence:
      - service: script.update_location
      - service: shell_command.cam6_1
      - delay:
          seconds: 2
      - service: shell_command.cam6_2
      - delay:
          seconds: 2
      - service: shell_command.cam6_3
      - delay:
          seconds: 2
      - service: shell_command.cam6_4
      - delay:
          seconds: 2
      - service: shell_command.cam6_5
      - condition: state # check that still noone came home with the last 10 sec
        entity_id: binary_sensor.someone_is_home
        state: 'off'
      - service: notify.pb 
        data:
          title: "Cam 6 pic 01"
          message: "motion"
          data:
            file: /tmp/106_1.jpg
      - service: notify.pb 
        data:
          title: "Cam 6 pic 02"
          message: "motion"
          data:
            file: /tmp/106_2.jpg
      - service: notify.pb 
        data:
          title: "Cam 6 pic 03"
          message: "motion"
          data:
            file: /tmp/106_3.jpg
      - service: notify.pb 
        data:
          title: "Cam 6 pic 04"
          message: "motion"
          data:
            file: /tmp/106_4.jpg
      - service: notify.pb 
        data:
          title: "Cam 6 pic 05"
          message: "motion"
          data:
            file: /tmp/106_5.jpg

