### ball living room
# SL, DS18B20
# -----------------------------------------------

light:
  - platform: mqtt ### cam illumino 102
    name: "dev102"
    state_topic: "255726482140298/r/light"
    command_topic: "255726482140298/s/light/dimm"
    rgb_state_topic: '255726482140298/r/light/dimm/color'
    rgb_command_topic: '255726482140298/s/light/dimm/color'
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"
    optimistic: false
    brightness_scale: 99

# -----------------------------------------------

homeassistant:
  customize:
    light.dev102:
      friendly_name: "Entrance C"
    binary_sensor.dev102_motion:
      friendly_name: "Entrance C"
    camera.cam_102:
      friendly_name: "Entrance"

# -----------------------------------------------

binary_sensor:
  - platform: mqtt
    state_topic: "255726482140298/r/motion"
    name: "dev102_motion"
    device_class: motion

# -----------------------------------------------

camera:
  - name: cam_102
    platform: generic
    still_image_url: http://192.168.2.102/cam_full.jpg

# -----------------------------------------------

shell_command:
  cam2_1: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_1.jpg
  cam2_2: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_2.jpg
  cam2_3: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_3.jpg
  cam2_4: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_4.jpg
  cam2_5: wget http://192.168.2.102/cam_full.jpg -O /tmp/102_5.jpg

# -----------------------------------------------

script:
  seq_102:
    sequence:
      - service: script.update_location
      - service: shell_command.cam2_1
      - delay:
          seconds: 2
      - service: shell_command.cam2_2
      - delay:
          seconds: 2
      - service: shell_command.cam2_3
      - delay:
          seconds: 2
      - service: shell_command.cam2_4
      - delay:
          seconds: 2
      - service: shell_command.cam2_5
      - condition: state # check that still noone came home with the last 10 sec
        entity_id: binary_sensor.someone_is_home
        state: 'off'
      - service: notify.pb 
        data:
          title: "Cam 2 pic 01"
          message: "motion"
          data:
            file: /tmp/102_1.jpg
      - service: notify.pb 
        data:
          title: "Cam 2 pic 02"
          message: "motion"
          data:
            file: /tmp/102_2.jpg
      - service: notify.pb 
        data:
          title: "Cam 2 pic 03"
          message: "motion"
          data:
            file: /tmp/102_3.jpg
      - service: notify.pb 
        data:
          title: "Cam 2 pic 04"
          message: "motion"
          data:
            file: /tmp/102_4.jpg
      - service: notify.pb 
        data:
          title: "Cam 2 pic 05"
          message: "motion"
          data:
            file: /tmp/102_5.jpg

