# -----------------------------------------------

homeassistant:
  customize:
    light.dev1:
      friendly_name: "Ball"
      retain: True
    binary_sensor.dev1_button:
      friendly_name: "Ball button"
    binary_sensor.dev1_button1s:
      friendly_name: "Ball button1s"
    binary_sensor.dev1_motion:
      friendly_name: "Ball motion"
      device_class: motion
    sensor.dev1_temperature:
      friendly_name: "Ball temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"

# -----------------------------------------------

sensor:
  - platform: energy_calc
    name: "Solar to home"
    net_id: "sensor.dev37_em_cur"
    gen_id: "sensor.kaco_194"
# -----------------------------------------------
  - platform: template
    sensors:
      energy_calc_home_from_solar:
        friendly_name: "Home from solar"
        icon_template: 'mdi:weather-sunny'
        unit_of_measurement: "%"
        value_template: "{{ states.sensor.energy_calc.attributes['Home_from_Solar_[%]'] }}"
# -----------------------------------------------
  - platform: template
    sensors:
      energy_calc_home:
        friendly_name: "Home"
        icon_template: 'mdi:weather-sunny'
        unit_of_measurement: "W"
        value_template: "{{ states.sensor.energy_calc.attributes['Home_[W]'] }}"
# -----------------------------------------------
