## Google Music Media Player
## Use this 'package.yaml' file to configure "gmusic_player"
media_player:
  - platform: gmusic_player
    username: !secret gmusic_user
    password: !secret gmusic_pw
    device_id: !secret gmusic_device_id
    token_path: /config/

input_select:
  gmusic_player_speakers:
    name: Speakers
    icon: mdi:speaker
    ## Add your media_players below
    options: # Example media_players
    - jkw_cast2
