binary_sensor:
  - platform: template
    sensors:
      harmony:
        value_template: false



script:
  chrome_pause:
    sequence:
      - service: media_player.media_play_pause
        entity_id: media_player.jkw_cast2

  tvvolumeup:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: VolumeUp
          device: 47580278
          num_repeats: 10
          delay_secs: 0.0
  tvmute:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: Mute
          device: 47580278
  tvvolumedown:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: VolumeDown
          device: 47580278
          num_repeats: 10
          delay_secs: 0.0
  firedown:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: DirectionDown
          device: 49174954
  fireup:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: DirectionUp
          device: 49174954
  fireok:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: OK
          device: 49174954
  fireleft:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: DirectionLeft
          device: 49174954
  fireright:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: DirectionRight
          device: 49174954
  firehome:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: Home
          device: 49174954
  tvoff:
    sequence:
      - service: remote.turn_on
        entity_id: remote.tvhub
        data:
          activity: "-1"
  start_fire:
    sequence:
      - service: remote.turn_on
        entity_id: remote.tvhub
        data:
          activity: "29555877"
  start_chromaudio:
    sequence:
      - service: remote.turn_on
        entity_id: remote.tvhub
        data:
          activity: "32486021"
  start_chrom:
    sequence:
      - service: remote.turn_on
        entity_id: remote.tvhub
        data:
          activity: "28707818"
  tvup:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: ChannelUp
          device: 53034729
  tvdown:
    sequence:
      - service: remote.send_command
        entity_id: remote.tvhub
        data:
          command: ChannelDown
          device: 53034729

