    
 
sensor:
  - platform: template
    sensors:
      kaco_194_kwh:
        friendly_name: "Solar kWh"
        icon_template: 'mdi:weather-sunny'
        unit_of_measurement: "kWh"
        value_template: "{{ states.sensor.kaco_194.attributes.kwh_today }}"
