notify:
  - platform: file
    name: filenotify_bat_1
    filename: /opt/battery_total_1.csv
  - platform: file
    name: filenotify_bat_2
    filename: /opt/battery_total_2.csv
  - platform: file
    name: filenotify_bat_3
    filename: /opt/battery_total_3.csv
  - platform: file
    name: filenotify_bat_4
    filename: /opt/battery_total_4.csv
  - platform: file
    name: filenotify_bat_5
    filename: /opt/battery_total_5.csv
  - platform: file
    name: filenotify_bat_6
    filename: /opt/battery_total_6.csv


automation:
  - alias: sensor_values_to_file_battery
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:55'
    action:
      - service: notify.filenotify_bat_1
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['bathroom_u_battery'].state }}"
      - service: notify.filenotify_bat_2
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['outside_battery'].state }}"
      - service: notify.filenotify_bat_3
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['carlo_battery'].state }}"
      - service: notify.filenotify_bat_4
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['livingroom_battery'].state }}"
      - service: notify.filenotify_bat_5
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['beamer_battery'].state }}"
      - service: notify.filenotify_bat_6
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor['entrance_battery'].state }}"

sensor:
  - platform: load_external
    name: long_term_battery_1
    feed_path: '/opt/battery_total_1.csv'
  - platform: load_external
    name: long_term_battery_2
    feed_path: '/opt/battery_total_2.csv'
  - platform: load_external
    name: long_term_battery_3
    feed_path: '/opt/battery_total_3.csv'
  - platform: load_external
    name: long_term_battery_4
    feed_path: '/opt/battery_total_4.csv'
  - platform: load_external
    name: long_term_battery_5
    feed_path: '/opt/battery_total_5.csv'
  - platform: load_external
    name: long_term_battery_6
    feed_path: '/opt/battery_total_6.csv'
