notify:
  - platform: file
    name: filenotify
    filename: /opt/counter_total.csv

automation:
  - alias: sensor_values_to_file
    initial_state: 'on'
    trigger:
      - platform: time
        at: '23:59:55'
    action:
      - service: notify.filenotify
        data_template: 
          message: "{{now().strftime('%Y-%m-%d')}},{{ states.sensor.dev16_em_tot.state }}"

sensor:
  - platform: load_external
    name: long_term_power
    feed_path: '/opt/counter_total.csv'
