# -----------------------------------------------
sensor:
  - platform: ical
    name: Packaging
    url: https://www.rmg-gmbh.de/download/Hamb%C3%BChren.ics
    id: 1
  - platform: ical
    name: Trash
    url: http://www.zacelle.de/privatkunden/muellabfuhr/abfuhrtermine/?tx_ckcellextermine_pi1%5Bot%5D=148&tx_ckcellextermine_pi1%5Bics%5D=0&tx_ckcellextermine_pi1%5Bstartingpoint%5D=234&type=3333
    id: 2
  - platform: ical
    name: Paper
    url: http://www.zacelle.de/privatkunden/muellabfuhr/abfuhrtermine/?tx_ckcellextermine_pi1%5Bot%5D=148&tx_ckcellextermine_pi1%5Bics%5D=2&tx_ckcellextermine_pi1%5Bstartingpoint%5D=234&type=3333
    id: 3

  - platform: template
    sensors:
      trash_0_rem:
        value_template: >-
          {{ states.sensor.ical_1.attributes.remaining }}
        unit_of_measurement: 'day'
      trash_1_rem:
        value_template: >-
          {{ states.sensor.ical_2.attributes.remaining }}
        unit_of_measurement: 'day'
      trash_2_rem:
        value_template: >-
          {{ states.sensor.ical_3.attributes.remaining }}
        unit_of_measurement: 'day'
# -----------------------------------------------
# -----------------------------------------------
automation:
  - alias: 'trash pickup msg'
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        hours: 19
        minutes: 00
        seconds: 00
      - platform: time_pattern
        hours: 17
        minutes: 00
        seconds: 00
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.trash_0_rem
          state: '1'
        - condition: state
          entity_id: sensor.trash_1_rem
          state: '1'
        - condition: state
          entity_id: sensor.trash_2_rem
          state: '1'
    action:
      - service: script.turn_on
        entity_id: script.seq_trash


# -----------------------------------------------

script:
  seq_trash:
    sequence:
      - service: notify.pb
        data_template:
          title: "Trash pickup tomorrow"
          message: >
           {% if is_state_attr("sensor.ical_1", "remaining","1") %} {{states.sensor.ical_1.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ical_2", "remaining","1") %} {{states.sensor.ical_2.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ical_3", "remaining","1") %} {{states.sensor.ical_3.attributes.friendly_name}} pickup tomorrow.{% endif %}
      - service: notify.pb_c
        data_template:
          title: "Trash pickup tomorrow"
          message: >
           {% if is_state_attr("sensor.ical_1", "remaining","1") %} {{states.sensor.ical_1.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ical_2", "remaining","1") %} {{states.sensor.ical_2.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ical_3", "remaining","1") %} {{states.sensor.ical_3.attributes.friendly_name}} pickup tomorrow.{% endif %}
