# -----------------------------------------------
sensor:
  - platform: trash
    regioncode: "148"

  - platform: template
    sensors:
      trash_0_rem:
        value_template: >-
          {{ states.sensor.trash_0.attributes.remaining }}
        unit_of_measurement: 'day'
      trash_1_rem:
        value_template: >-
          {{ states.sensor.trash_1.attributes.remaining }}
        unit_of_measurement: 'day'
      trash_2_rem:
        value_template: >-
          {{ states.sensor.trash_2.attributes.remaining }}
        unit_of_measurement: 'day'
      trash_3_rem:
        value_template: >-
          {{ states.sensor.trash_3.attributes.remaining }}
        unit_of_measurement: 'day'
# -----------------------------------------------
homeassistant:
  customize:
    sensor.trash_0:
      rgb_color: [160,160,160]
    sensor.trash_1:
      rgb_color: [30,120,10]
    sensor.trash_2:
      rgb_color: [31,78,155]
    sensor.trash_3:
      rgb_color: [255,152,0]
# -----------------------------------------------
group:
  trash:
    name: Trash
    control: hidden
    icon: mdi:comment-multiple-outline
    view: no
    entities:
      - sensor.trash_0
      - sensor.trash_1
      - sensor.trash_2
      - sensor.trash_3
# -----------------------------------------------
automation:
  - alias: 'pickup_0'
    initial_state: 'on'
    trigger:
      - platform: time
        hours: 21 #19
        minutes: 15 #30
        seconds: 00
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: sensor.trash_0_rem
          state: '0'
        - condition: state
          entity_id: sensor.trash_1_rem
          state: '0'
        - condition: state
          entity_id: sensor.trash_2_rem
          state: '0'
        - condition: state
          entity_id: sensor.trash_3_rem
          state: '0'
    action:
     service: notify.pb
     data_template:
       title: "Trash pickup tomorrow"
       message: >
        {% if is_state_attr("sensor.trash_0", "remaining","0") %} {{states.sensor.trash_0.attributes.friendly_name}} pickup tomorrow.{% endif %}
        {% if is_state_attr("sensor.trash_1", "remaining","0") %} {{states.sensor.trash_1.attributes.friendly_name}} pickup tomorrow.{% endif %}
        {% if is_state_attr("sensor.trash_2", "remaining","0") %} {{states.sensor.trash_2.attributes.friendly_name}} pickup tomorrow.{% endif %}
        {% if is_state_attr("sensor.trash_3", "remaining","0") %} {{states.sensor.trash_3.attributes.friendly_name}} pickup tomorrow.{% endif %}


# -----------------------------------------------

