# -----------------------------------------------
sensor:
  - platform: ics
    name: Packaging
    url: https://www.rmg-gmbh.de/download/Hamb%C3%BChren.ics
    show_blank: "blank"
    id: 1
    icon: "mdi:recycle"

  - platform: ics
    name: Trash
    url: http://www.zacelle.de/privatkunden/muellabfuhr/abfuhrtermine/?tx_ckcellextermine_pi1%5Bot%5D=148&tx_ckcellextermine_pi1%5Bics%5D=0&tx_ckcellextermine_pi1%5Bstartingpoint%5D=234&type=3333
    id: 2
    icon: "mdi:trash-can-outline"

  - platform: ics
    name: Paper
    url: http://www.zacelle.de/privatkunden/muellabfuhr/abfuhrtermine/?tx_ckcellextermine_pi1%5Bot%5D=148&tx_ckcellextermine_pi1%5Bics%5D=2&tx_ckcellextermine_pi1%5Bstartingpoint%5D=234&type=3333
    id: 3
    icon: "mdi:package-variant"

  - platform: template
    sensors:
      ics_4_txt:
        value_template: '{{ states.sensor.ics_4.attributes.description}} @ {{states.sensor.ics_4.state}}'
        friendly_name: "Work Next"

# -----------------------------------------------
# -----------------------------------------------
automation:
  - alias: 'trash pickup msg'
    initial_state: 'on'
    trigger:
      - platform: time_pattern
        hours: 19
        minutes: 00
        seconds: 00
      - platform: time_pattern
        hours: 17
        minutes: 00
        seconds: 00
    condition:
      condition: or
      conditions:
        - condition: template
          value_template: "{{ state_attr('sensor.ics_1', 'remaining') == 1 }}"
        - condition: template
          value_template: "{{ state_attr('sensor.ics_2', 'remaining') == 1 }}"
        - condition: template
          value_template: "{{ state_attr('sensor.ics_3', 'remaining') == 1 }}"
    action:
      - service: script.turn_on
        entity_id: script.seq_trash


# -----------------------------------------------

script:
  seq_trash:
    sequence:
      - service: notify.pb
        data_template:
          title: "Pickup tomorrow"
          message: >
           {% if is_state_attr("sensor.ics_1", "remaining",1) %} {{states.sensor.ics_1.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ics_2", "remaining",1) %} {{states.sensor.ics_2.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ics_3", "remaining",1) %} {{states.sensor.ics_3.attributes.friendly_name}} pickup tomorrow.{% endif %}
      - service: notify.pb_c
        data_template:
          title: "Pickup tomorrow"
          message: >
           {% if is_state_attr("sensor.ics_1", "remaining",1) %} {{states.sensor.ics_1.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ics_2", "remaining",1) %} {{states.sensor.ics_2.attributes.friendly_name}} pickup tomorrow.{% endif %}
           {% if is_state_attr("sensor.ics_3", "remaining",1) %} {{states.sensor.ics_3.attributes.friendly_name}} pickup tomorrow.{% endif %}
