weather:
  - platform: darksky
    api_key: !secret darksky_key

# -----------------------------------------------

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
    monitored_conditions:
      - icon
      - temperature
      - temperature_high
    scan_interval:
      minutes: 5

  - platform: mqtt
    state_topic: "weather_reload_trigger"
    name: "weather_reload_trigger"

# -----------------------------------------------

camera:
  - platform: generic
    still_image_url: https://www.dwd.de/DWD/wetter/radar/radfilm_brd_akt.gif?{{states('sensor.weather_reload_trigger')}}
    name: cam_weather1
    limit_refetch_to_url_change: true
  - platform: generic
    still_image_url: https://www.dwd.de/DWD/wetter/radar/radfilm_nib_akt.gif?{{states('sensor.weather_reload_trigger')}}
    name: cam_weather2
    limit_refetch_to_url_change: true
