weather:
  - platform: darksky
    api_key: !secret darksky_key

sensor:
  - platform: darksky
    api_key: !secret darksky_key
    forecast:
      - 0
    monitored_conditions:
      - icon
      - temperature
      - temperature_high
    scan_interval:
      minutes: 5
