homeassistant:
  customize:
    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: "Mr Thielmann"
    automation.Start_cleaning_when_alone:
      friendly_name: "Autostart cleaning"
    group.vac:
      friendly_name: "Vacuuming"
    

group:
  vac:
    control: hidden
    icon: mdi:thermometer
    view: no
    entities:
      - vacuum.xiaomi_vacuum_cleaner
      - input_boolean.cleaning_done_today
      - sensor.vac_triggered
      - automation.Start_cleaning_when_alone


sensor:
  - platform: template
    sensors:
      vac_triggered:
        value_template: '{{ (as_timestamp(states.input_boolean.cleaning_done_today.last_changed)) |   timestamp_custom("%A, %d %h %H:%M") }}'
        friendly_name: "Cleaning last triggered"

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.75
    token: 4d53785148576d5865734d4d4d595867

input_boolean:
  cleaning_done_today:
    name: Cleaning done today
    initial: off
    icon: mdi:check


automation:
  - alias: "Reset_cleaning_done"
    trigger:
      - platform: time
        hours:   00
        minutes: 00
        seconds: 00
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.cleaning_done_today

  - alias: "Start_cleaning_when_alone"
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_is_home
        to: 'off'
    condition:
      - condition: state
        entity_id: input_boolean.cleaning_done_today
        state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.activate_cleaning

  - alias: "Stop_cleaning_when_not_alone"
    trigger:
      - platform: state
        entity_id: binary_sensor.someone_is_home
        to: 'on'
    action:
      - service: script.turn_on
        entity_id: script.deactivate_cleaning



script:
  activate_cleaning:
    sequence:
      - alias: "Switch vac on"
        service: homeassistant.turn_on
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - alias: "set reminder"
        service: homeassistant.turn_on
        entity_id: input_boolean.cleaning_done_today
 
  deactivate_cleaning:
    alias: "deactivate cleaning"
    sequence:
      - alias: "Switch vac off"
        service: homeassistant.turn_off
        entity_id: vacuum.xiaomi_vacuum_cleaner
      - condition: template
        value_template: >
           {{ (as_timestamp(now()) - as_timestamp(states.switch.zone_1.last_changed)) < 30*60 }}
      - alias: "re_set reminder"
        service: homeassistant.turn_off
        entity_id: input_boolean.cleaning_done_today
