shell_command:
  camxia1_1: wget http://192.168.2.42/snapshot.jpg -O /tmp/xia1_1.jpg
  camxia1_2: wget http://192.168.2.42/snapshot.jpg -O /tmp/xia1_2.jpg
  camxia1_3: wget http://192.168.2.42/snapshot.jpg -O /tmp/xia1_3.jpg
  camxia1_4: wget http://192.168.2.42/snapshot.jpg -O /tmp/xia1_4.jpg
  camxia1_5: wget http://192.168.2.42/snapshot.jpg -O /tmp/xia1_5.jpg


camera:
  - platform: generic
    still_image_url: http://192.168.2.42/snapshot.jpg
    name: cam_xia1

automation:
  - alias: alarm_system_cxia1
    initial_state: False
    hide_entity: False
    trigger:
      - platform: state
        entity_id: binary_sensor.dev6_motion
        to: 'on'
    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: input_boolean.alarm_System
          state: 'on'
        - condition: state
          entity_id: binary_sensor.someone_is_home
          state: 'off'
        - condition: state
          entity_id: vacuum.xiaomi_vacuum_cleaner
          state: 'off'
    action:
      - service: script.turn_on
        entity_id: script.seq_xia1


script:
  seq_xia1:
    sequence:
      - service: script.update_location
      - service: shell_command.camxia1_1
      - delay:
          seconds: 2
      - service: shell_command.camxia1_2
      - delay:
          seconds: 2
      - service: shell_command.camxia1_3
      - delay:
          seconds: 2
      - service: shell_command.camxia1_4
      - delay:
          seconds: 2
      - service: shell_command.camxia1_5
      - condition: state # check that still noone came home with the last 10 sec
        entity_id: binary_sensor.someone_is_home
        state: 'off'
      - service: notify.pb 
        data:
          title: "Cam xia1 pic 01"
          message: "motion"
          data:
            file: /tmp/xia1_1.jpg
      - service: notify.pb 
        data:
          title: "Cam xia1 pic 02"
          message: "motion"
          data:
            file: /tmp/xia1_2.jpg
      - service: notify.pb 
        data:
          title: "Cam xia1 pic 03"
          message: "motion"
          data:
            file: /tmp/xia1_3.jpg
      - service: notify.pb 
        data:
          title: "Cam xia1 pic 04"
          message: "motion"
          data:
            file: /tmp/xia1_4.jpg
      - service: notify.pb 
        data:
          title: "Cam xia1 pic 05"
          message: "motion"
          data:
            file: /tmp/xia1_5.jpg

