automation:
  - alias: alarm_system_roundshot
    initial_state: True
    hide_entity: False
    trigger:
      - platform: mqtt
        topic: "alarm/round_shot"
    action:
      - service: script.turn_on
        entity_id: script.seq_xia_round


script:
  seq_xia_round:
    sequence:
      - service: shell_command.camxia1_1
      - service: notify.pb 
        data:
          title: "Roundshot"
          message: "cam 1"
          data:
            file: /tmp/xia1_1.jpg
      - service: shell_command.camxia2_1
      - service: notify.pb 
        data:
          title: "Roundshot"
          message: "cam 2"
          data:
            file: /tmp/xia2_1.jpg
      - service: shell_command.camxia3_1
      - service: notify.pb 
        data:
          title: "Roundshot"
          message: "cam 3"
          data:
            file: /tmp/xia3_1.jpg
      - service: shell_command.camxia4_1
      - service: notify.pb 
        data:
          title: "Roundshot"
          message: "cam 4"
          data:
            file: /tmp/xia4_1.jpg
      - service: shell_command.camxia5_1
      - service: notify.pb 
        data:
          title: "Roundshot"
          message: "cam 5"
          data:
            file: /tmp/xia5_1.jpg

