homeassistant:
  customize:
    vacuum.xiaomi_vacuum_cleaner:
      friendly_name: "Thielmann Sr"
    vacuum.xiaomi_vacuum_cleaner_2:
      friendly_name: "Thielmann Jr"
    automation.vac_start_cleaning_when_alone:
      friendly_name: "Autostart cleaning"    

sensor:
  - platform: template
    sensors:
      vac_triggered_0:
        value_template: '{{ (as_timestamp(states.input_boolean.cleaning_done_today_0.last_changed)) |   timestamp_custom("%A, %d %h %H:%M") }}'
        friendly_name: "Cleaning last triggered 1"
  - platform: template
    sensors:
      vac_triggered_1:
        value_template: '{{ (as_timestamp(states.input_boolean.cleaning_done_today_1.last_changed)) |   timestamp_custom("%A, %d %h %H:%M") }}'
        friendly_name: "Cleaning last triggered 2"

vacuum:
  - platform: xiaomi_miio
    host: 192.168.2.30
    token: !secret xiaomi_token
    name: xiaomi_vacuum_cleaner
  - platform: xiaomi_miio
    host: 192.168.2.92
    token: !secret xiaomi_token2
    name: xiaomi_vacuum_cleaner_2

input_boolean:
  cleaning_done_today_0:
    name: Sr Cleaning done today
    initial: off
    icon: mdi:check
  cleaning_done_today_1:
    name: Jr Cleaning done today
    initial: off
    icon: mdi:check
  autostart_cleaning:
    name: Autostart cleaning
    initial: on
    icon: mdi:check


