# -----------------------------------------------

homeassistant:
  customize:
    light.dev62:
      friendly_name: "A12"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev62"
    fname: "62 A12"

