
homeassistant:
  customize:
    switch.dev39_gpio_12:
      friendly_name: "Dehumidifier"
      icon: mdi:fan
# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev39"
    fname: "39 Dehumidifier"
  - platform: mqtt
    state_topic: "dev39_drytime"
    name: "dev39_heattime"
    unit_of_measurement: "min"

# -----------------------------------------------
