# -----------------------------------------------

homeassistant:
  customize:
    light.dev35:
      friendly_name: "Spielecke Wand"
    binary_sensor.dev35_button:
      friendly_name: "Spielecke Wand button"
    binary_sensor.dev35_button1s:
      friendly_name: "Spielecke Wand button1s"
    binary_sensor.dev35_motion:
      friendly_name: "Spielecke Wand motion"
      device_class: motion
    sensor.dev35_temperature:
      friendly_name: "Spielecke Wand temperature"
      unit_of_measurement: "°C"
      icon: "mdi:thermometer"
      device_class: "temperature"
    sensor.dev35_adc:
      friendly_name: "Spielecke Wand"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev35"
    fname: "35 Spielecke Wand"

# -----------------------------------------------
