### touch bedroom
# SL
# -----------------------------------------------

light:
  - platform: mqtt ### 
    name: "dev59"
    state_topic: "dev59/r/light"
    command_topic: "dev59/s/light"
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev59"
    fname: "59"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev59:
      friendly_name: "59"
      icon: "mdi:lamp"

# -----------------------------------------------

