### touch bedroom
# SL
# -----------------------------------------------

light:
  - platform: mqtt ### 
    name: "dev58"
    state_topic: "dev58/r/light"
    command_topic: "dev58/s/light"
    retain: True
    qos: 0
    payload_on: "ON"
    payload_off: "OFF"

# -----------------------------------------------

sensor:
  - platform: mqtt_jkw
    name: "dev58"
    fname: "58 SL"

# -----------------------------------------------

homeassistant:
  customize:
    light.dev58:
      friendly_name: "58"
      icon: "mdi:lamp"

# -----------------------------------------------

