# -----------------------------------------------------------
# -----------------------------------------------------------

input_select:
  light_livingroom:
    name: mode livingroom
    options:
     - all on
     - couch
     - table
     - all off
    icon: mdi:account-multiple
    initial: all off

# -----------------------------------------------------------
# -----------------------------------------------------------

automation:

# ------------------- rule ------------------------
  - alias: joiner_livingroom_change
    initial_state: True
    hide_entity: False
    trigger: 
      - platform: state
        entity_id: light.joiner_livingroom
    action:
      service: input_select.select_option
      data_template: 
        entity_id: input_select.light_livingroom
        option: > 
         {% if is_state('light.joiner_livingroom','on') %}
          all on
         {% else %}
          all off
         {% endif %}
# ------------------- rule ------------------------


# ------------------- rule ------------------------
  - alias: 'next option next'
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "dev23/r/button"
    condition:
      condition: template
      value_template: '{{ (as_timestamp(now())-as_timestamp(states.automation.next_option_toggle.attributes.last_triggered) < 3) or (as_timestamp(now())-as_timestamp(states.automation.next_option_next.attributes.last_triggered) < 3)  }}'
    action:
      service: input_select.select_next
      data_template: 
        entity_id: input_select.light_livingroom
# ------------------- rule ------------------------

# ------------------- rule ------------------------
  - alias: 'next option toggle'
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "dev23/r/button"
    condition:
      condition: template
      value_template: '{{ (((states.automation.next_option_next.attributes.last_triggered is none) or (as_timestamp(now())-as_timestamp(states.automation.next_option_next.attributes.last_triggered) > 3 ))) and (((states.automation.next_option_toggle.attributes.last_triggered is none) or (as_timestamp(now())-as_timestamp(states.automation.next_option_toggle.attributes.last_triggered) > 3 ))) }}'
    action:
      service: input_select.select_option
      data_template: 
        entity_id: input_select.light_livingroom
        option: > 
         {% if is_state('input_select.light_livingroom','all off') %}
          all on
         {% else %}
          all off
         {% endif %}
# ------------------- rule ------------------------

# ------------------- rule ------------------------
  - alias: 'next option exec'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.light_livingroom
    action:
      service: script.turn_on
      data_template: 
        entity_id: >
         {% if is_state('input_select.light_livingroom','all off') %}
          script.seq_all_off
         {% elif is_state('input_select.light_livingroom','couch') %}
          script.seq_couch
         {% elif is_state('input_select.light_livingroom','table') %}
          script.seq_table
         {% elif is_state('input_select.light_livingroom','all on') %}
          script.seq_all_on
         {% endif %}
# ------------------- rule ------------------------

# -----------------------------------------------------------
# -----------------------------------------------------------

script:

  seq_couch:
    sequence:
      - service: light.turn_on
        entity_id: light.dev1
      - service: light.turn_on
        entity_id: light.dev21
      - service: light.turn_off
        entity_id: light.dev11
      - service: light.turn_off
        entity_id: light.dev7

  seq_table:
    sequence:
      - service: light.turn_off
        entity_id: light.dev1
      - service: light.turn_off
        entity_id: light.dev21
      - service: light.turn_on
        entity_id: light.dev11
      - service: light.turn_on
        entity_id: light.dev7

  seq_all_off:
    sequence:
      - service: light.turn_off
        entity_id: light.dev1
      - service: light.turn_off
        entity_id: light.dev21
      - service: light.turn_off
        entity_id: light.dev11
      - service: light.turn_off
        entity_id: light.dev7

  seq_all_on:
    sequence:
      - service: light.turn_on
        entity_id: light.dev1
      - service: light.turn_on
        entity_id: light.dev21
      - service: light.turn_on
        entity_id: light.dev11
      - service: light.turn_on
        entity_id: light.dev7
# -----------------------------------------------------------
# -----------------------------------------------------------
